tile-window.lisp
This adds an "unmaximize" command that sets a flag on a window to try and size it according to the program-suggested size instead of optimizing it. Usefulness includes checking how something looks in a standard 80x25 xterm, viewing a video at native resolution, or unbreaking windows that erroneously don't flag themselves as dialogs.
=> Add ability for tiled windows to not be maximized

tile-window.lisp
=> Adds the pull-from-windowlist command.

command.lisp, primitives.lisp, stumpwm.texi.in
I hope the docstrings are good enough? Would you like to have examples too in them?
=> Command hooks

color.lisp, input.lisp, message-window.lisp
Workaround for this - https://github.com/stumpwm/stumpwm-contrib/issues/21
=> Sans invert rect

help.lisp
=> fix crash when trying to display map with no bindings

stumpwm.lisp
This is a minor change intended to make `run-expired-timers` easier to understand. `sort-timers` could benefit from moving the re-scheduling logic out of it. Maybe returning a third value, `to-reschedule` and a separate function `reschedule-timers`.
One thing I'm unsure of is if `execute-timers` is necessary or if `(map nil 'execute-timer pending)` is clear enough.
Another thing is that expired or expired-timers may be a better name than pending in `sort-timers`
Thoughts?
=> Refactor RUN-EXPIRED-TIMERS

events.lisp, primitives.lisp, screen.lisp, window.lisp, wrappers.lisp
I don't think any of these changes will be controversial (except maybe the screen initialization), but there are enough changes that I think a pull request is more appropriate than pushing directly.
None of these changes should be externally noticeable, but some more testing is in order to make sure I didn't miss anything.
=> Clean up a variety of things

events.lisp, head.lisp, mode-line-formatters.lisp, mode-line.lisp, primitives.lisp, stumpwm.asd
The commit messages should be enough to explain what's happening here.
The external interface didn't change, so this is backwards compatible in that regard.
=> Reorganize and clean up the mode line

window.lisp
Previously the message was only sent when *CURRENT-EVENT-TIME* was
non-NIL. This caused problems in IntelliJ IDEA when a dialog window
was dismissed using the ESC key which then resulted in the cursor not
being active in the main edit window in the application.
=> Always send WM_TAKE_FOCUS when a window is focused.

primitives.lisp
Removes all functions from a hook.
=> Add: `remove-all-hooks`

.travis.yml, command.lisp, events.lisp, group.lisp, package.lisp, primitives.lisp, stumpwm.asd
And add some commits showing why we would want to include the dependency.
=> Depend on Alexandria

group.lisp
Use ASSERT instead of IF to check for conditions to be met. Split the retrieval
or creation of the group into a separate function.
Another alternative would be to use flet to define ensure-group as a local function, but in my opinion local functions tend to clutter the function body.
Another thing to consider is if it would be a good idae to move the group creation to its own MAKE-GROUP constructor. It appears that add-group is the only place in the code base where groups are instantiated.
Something I'm left wondering is, would it be wise to allow a new group name to be provided when the assertion fails?
=> Refactor ADD-GROUP

interactive-keymap.lisp, iresize.lisp, stumpwm.asd, stumpwm.texi.in
=> Initial interactive command implementation

stumpwm.lisp, user.lisp, wrappers.lisp
Starting to remove code for non-sbcl implementations. In some cases removed the functions altoghther, in others left the function but removed all but the SBCL implementation
=> Wrappers cleanup

group.lisp, window.lisp
Needed this as soon as I could have mixed floating and tile windows.
=> Add support for keeping a floating window always on top

make-image.lisp.in
=> Revert "Remove un-needed SBCL_HOME reference"

head.lisp
As discussed on https://github.com/stumpwm/stumpwm/pull/344/files#r109670383
=> NUMBER-HEADS: Restore loop implementation

.gitignore, stumpwm.texi.in
Hi!
After many years as a stump user, I thought I should probably actually read the manual. Eight pages in I find I've underlined a bunch of stuff that's wrong, or could be improved. I thought I'd share them here, you can cherry pick the stuff you want if not all is good.
Let me know if I should keep going as I read pages 10-70 as well.
=> Manual fixes

stumpwm.texi.in
A bit of a continuation of #358, were I nitpick the manual. (Now I've reached page 15.)
This pull request could be kept open, and I'll keep pushing to it as I find more stuff to fix, if you whish. Not sure what you prefer in this project.
=> Manual/documentation: more nitpicking 

bindings.lisp, command.lisp, input.lisp, interactive-keymap.lisp, mode-line.lisp, primitives.lisp, stumpwm.texi.in, user.lisp
Some more typo fixes. (Note to self: I'm now on page 33 of 70 on pdf-version of manual).
=> More documentation fixes 2

color.lisp, primitives.lisp, stumpwm.texi.in
I've finished reading the manual, and thus the trilogy has come to its grand finale, with this last PR.
Have a look, and comment, and I'll rebase/modify as needed.
=> More documentation fixes, part 3

command.lisp
Minor changes to use more idiomatic code
=> COMMAND.LISP: Use when-let when applicable

events.lisp
=> MAYBE-MAP-WINDOW: Remove redundant IF

input.lisp
This is useful for e.g. pinentry that wants to ask for a passphrase
after explaining which key needs to be unlocked.
=> Add support for multi-lines prompt.

window.lisp
Using ```alexandria:if-let``` instead of nested let and if
=> Simplify windowlist command 

help.lisp
* Using if-let instead of nested let and if
* Bind result of ```(mapcar 'print-key keys)``` in variable
=> Simplify describe-key command

window.lisp
Kill all windows in the current group
=> Add KILL-WINDOWS command

stumpwm.texi.in
#421 gkill-other
#424 kill-windows-current-group
#427 kill-windows-other
=> Add manual for commands

AUTHORS, primitives.lisp, tile-window.lisp, window-placement.lisp
=> Window placement improvements

.travis.yml
Mainly so I don't get an email every time I push code
=> Update Travis-CI notifications

stumpwm.texi.in
Remove unnecessary introduction. My main problem with the section was the use of the word intuitively.
Don't recommend the -a option in commit. It stages all changes from all
files being track.
=> stumpwm.texi: Update HACKING copying

tile-group.lisp
This is a follow-up to f03c4cc623e114e7e58012dcac64593492bee505
=> Follow-up fixing #475

group.lisp
Extract NETWM-UPDATE-GROUP from NETWM-UPDATE-GROUPS.
ADD-GROUP: Don't include newline in the error message. Pass NAME as a
place so SBCL can provide a restart to provide a new NAME when the given
names was not valid.
GRENAME Command: Extract the main functionality of the code to %GRENAME
leaving only the precondition checks in the body of the command. The
resulting code has less nesting.
=> GROUP.lisp: Miscellaneous Refactor

font-rendering.lisp
This reverts commit ca776d191863e303bd20fa0a420dbc4fe14356e8.
=> Revert "DRAW-IMAGE-GLYPHS"

command.lisp, input.lisp
=> Use a separate variable for shell history than command history.

primitives.lisp
Moved w (from uvxWyz to uvWxyz).
=> Fix alphabet in *frame-number-map*

head.lisp
Ditto. This prevents the crash reported in #610
=> Work-around for issue #610.

bindings.lisp, tile-group.lisp, tile-window.lisp, window.lisp
With tis PR I try to improve the experience in float groups (issue #612)
Now in float group the following commands are available:
next, prev, other, fullscreen
=> Float group improvement

events.lisp, primitives.lisp, stumpwm.texi.in
Support running custom code after a click event.
=> Add *click-hook*

window.lisp
We can't use XLIB:WM-NAME as it doesn't conform to the ICCM
standard. It doesn't use the type of the property to decode the
octets.
In the case the property type is STRING there is some additional
translation needed which XLIB:CARD8->CHAR implements. Reuse that.
STRING as a type or a target specifies the ISO Latin-1 character set
plus the control characters TAB (octal 11) and NEWLINE (octal
12). The spacing interpretation of TAB is context dependent. Other
ASCII control characters are explicitly not included in STRING at
the present time.
from https://tronche.com/gui/x/icccm/sec-2.html#s-2.7.1
REF: https://tronche.com/gui/x/icccm/sec-4.html#s-4.1.2.1
=> Add XWIN-WM-NAME

window.lisp
Look at explanation [here](https://github.com/stumpwm/stumpwm/issues/641). To put it short: uxterm on FreeBSD puts UTF-8 encoded string in property WM_NAME of type STRING. This causes StumpWM to crash while decoding this string.
=> Catch TYPE-ERROR when decoding window names.

command.lisp, group.lisp, menu-declarations.lisp, menu-definitions.lisp, primitives.lisp
This adds a couple conservative edits to the group selection UI suggested in https://github.com/stumpwm/stumpwm/issues/690
and fixes some documentation and messages.
=> groups fixes

input.lisp
Adds a bare-minimum display of possible completions for input. The input line works the same as before, but displays possible completions rather than keeping them invisible. History, tab completion, etc. are not affected.
[screenshot](https://spensertruex.com/static/input-complete.png)
Since it does not do regex search, but instead just shows the completions in order, it won't interfere with "muscle memory" or any such thing. Just makes it easier to spell things correctly and learn what is available.
=> Show completions with input function

bindings.lisp
Remove just one split.  BTW screen uses this binding already.
=> Add binding "X" to remove-split

stumpwm.texi.in
* Added correct menu entries for the chapter on 'Miscellaneous Commands'
* Added a previous node entry for a sub-section in 'Miscellaneous Commands'
=> Fix issues in generating info pages

tile-group.lisp
If the stack unwinds during `choose-frame-by-number` (this can be triggered for instance by pressing backspace while choosing a frame), the little windows with the frame numbers in them won't be cleaned up, leaving them sitting on the screen. This change puts the cleanup code for the windows and the frame borders in an `unwind-protect` form so that they will be cleaned up properly.
After the change, this cleanup code will be executed after the forms which find the actual frame object, while it used to be executed before those forms, but as far as I can tell this doesn't make any difference to the behaviour of the code.
=> Clean up choose-frame-by-number decorations when unwinding occurs

floating-group.lisp
Tested on two systems.
PR in two commits so that is easier to see what changed in GitHub.
=> resize float windows: snap to closest corner and resize/move acc. to that corner

module.lisp
=> use PUSH to add to *load-path* and asdf:*central-registry*

mode-line.lisp
spotted by Joram Schrijver and Philip Adams
see https://github.com/stumpwm/stumpwm/pull/780#pullrequestreview-407654086 and https://github.com/stumpwm/stumpwm/issues/777#issuecomment-625352294
=> invert check for mode-line cleanup

tile-window.lisp
just like `windowlist` command does
=> pull-from-windowlist allows custom window-format

primitives.lisp, tile-group.lisp, tile-window.lisp, window-placement.lisp
Cleaned up the commits and opening a new pull request to make `define-frame-preference` handle auto-floating windows in tiling groups. Previous pull request was #781.
=> Float windows in tiling groups using `define-frame-preference`

primitives.lisp
It is documented on the docs but not exported... fixing this.
=> Export documented property

input.lisp
Hello again!
Completion candidates during completing-read can now be refined in a customizable
way. The `*input-refine-candidates-fn*` can be set to customize candidate
refinement. This parameter can be used to filter or sort candidates in novel ways.
By default, completion candidates are refined by prefix in unsorted order to maintain
backwards compatibility. Another refinement function, `input-refine-regexp`, is
implemented, which provides similar behavior to select-from-menu. That is, it refines
candidates by splitting the input string by space and treating each word as a regexp
to be matched.
I attached a screencast below of what the `input-refine-regexp` function looks like when
run with `colon`. It  looks a lot like `select-from-menu`, but without the drawbacks
of losing the command …
=> Allow refining input completion candidates

tile-window.lisp
=> Do not put a border around the only window

.github/workflows/test.yml, AUTHORS, Dockerfile
Build and run tests inside a dockerfile with every push and pull request.
This will help to ensure that the build doesn't break with changes.
=> GitHub actions CI

AUTHORS, manual.lisp
It really bothered me that the manual contained a bunch of useless lines starting with "@@@" so I learned why, how and when just to add one letter that fixes this issue. 
I found this regression was introduced by #728 about two years ago, and nobody since then noticed or cared enough to fix it. I'm happy to finally get on this.
=> Small manual generation fix 

message-window.lisp, tile-group.lisp
=> Redraw frame indicator and outline on resolution change

tile-group.lisp
=> Hide frame indicator after command `only`

ioloop.lisp
On my system (FreeBSD 13.1-RELEASE) #1011 caused errors when `sb-unix:unix-fast-select` returned `nil` (I'm not sure why this would happen in the first place). This change ignores these values and resolves the issue for me, please let me know if there's a better solution.
Thanks!
=> Handle nil values returned by sb-unix:unix-fast-select

kmap.lisp
Attempt to improve the user experience when an incorrect key string is given to `kbd` and friends by providing a hint on what was incorrect.
We can't really provide a good reason for failure for strings like `"-ret"`, because we can't really tell if the user misspelled the key signifier, forgot the leading modifier character, or actually wanted to bind to a key called `-ret`, which doesn't exist by default. Don't include a hint in this case to avoid getting it wrong.
=> Improve kbd function by adding a diagnostic message in some error cases

floating-group.lisp, group.lisp, head.lisp, message-window.lisp, stumpwm.texi.in, tests/integration-tests/testcases/issue-1031.sh, tests/integration-tests/testcases/issue-1032.sh, tests/integration-tests/testcases/test-basic-iresize.sh, tests/integration-tests/tests-expected-to-fail, tile-group.lisp, tile-window.lisp, user.lisp
NOTE: This PR depends on PR #1023.
Only a few commits are unique to this PR.
Fixes #928.
Fixes #1015.
Fixes #1016.
Fixes #1031.
Fixes #1032.
=> Improve resizing

manual.lisp
This PR changes how functions macros and commands are printed in the manual to only print the arguments symbols in the argument list instead of the whole argument when printing optional and key arguments.  This addresses issue #1055.  When printing default values lines are restricted to 80 characters long, with every value on its own line arranged in a table-esq format.  If an argument name is too long (leaving less than 30 characters width to print the default value in) then the default value is printed on a line below the argument and indented. 
For example, the macro `defprogram-shortcut` now prints as
```
-- Macro: defprogram-shortcut name &key command props map key pullp
pull-name pull-key
Default Values:
command    (string-downcase (string stumpwm::name))
props      `'(:class …
```
=> Improve function, macro, and command printing in the manual by separating default values from argument lists

time.lisp
=> Fix time-tz

primitives.lisp
There was a [fixme](https://github.com/stumpwm/stumpwm/blob/9b5e0cfd19d0dfb18e284ac140431a2685afbe3e/primitives.lisp#L971) saying the previous implementation was horribly inefficient, so I tried to improve it. The replacement is, um, a little bit bigger. But. It _is_ more efficient.
Also, new function - replace-ranges - that may be useful elsewhere, maybe. It has a docstring. It's half the function. And, I can't name things well.
~My spider is named Jumpy. She jumps.~
In simpler cases, though, this doesn't really run that much quicker, if at all, though its performance scales a lot better.
But, it almost always conses a lot less? From consing 70% as much to 10% or less - it, well. It scales better. Also looks less cryptic to me?
Note, how I tested:
I tested it in loops of a million, and …
=> Patch to redo format-expand

tile-group.lisp
=> Do not change focus on scroll

tile-group.lisp
=> Do not update mode-line on click unless window has changed

configure.ac, version.lisp.in
=> Supporting reproducible builds.

ioloop.lisp, make-image.lisp.in, stumpwm.lisp, stumpwm.texi.in, timers.lisp
=> Reworked IO loop, simplification & removing restarts.

stumpwm.texi.in
This adds a Table of Contents to the manual, improving navigation in the generated PDF.
=> Include table of contents in the manual

stumpwm.texi.in
=> Fixing the custom type example in the docs.
