stumpwm/stumpwm

- window.lisp
[Muse sequencer](http://muse-sequencer.org/) has some strange kind of subwindows, for those window-by-id sometimes (e.g. after switching to other desktop and back) returns false.
I don't know if it is the best way to workaround, but works well for me.
> Workaround for Muse sequencer

- stumpwm.lisp
Now that we're using ~/.stumpwm.d for modules and data, I'd like the option to put StmpWM's init file in that directory. I've added "~/.stumpwm.d/init.lisp" as an init file StumpWM will search for. The traditional ~/.stumpwmrc continues to have the highest priority, followed by this init.lisp, then the xdg and system-wide versions.
> Add ~/.stumpwm.d/init.lisp as an init file.

- AUTHORS
- stumpwm.texi.in
This is preliminary work for adding an 'Init File' node to the StumpWM manual. It's a basic introduction to the concept, and lists the possible names and locations available for init files. I'm completely new to Texinfo authoring, so I invite comments, additions, corrections, flames, snorts of derision... but mostly those first three things.
> Add 'Init File' section to Info manual.

- manual.lisp
Adds complete support for Clozure CL (CCL) to manual.lisp. Specifically, CCL wasn't extracting arglists from StumpWM source to fill out the manual references. It will now. ;)
> Fix #188: Missing arguments in manual when built with CCL.

- workarounds.lisp
The bug was fixed ~15 days after the 172f13e144268e51a87f314cb771dc4513943c78 commit, as you can see from: https://github.com/sharplispers/clx/commit/c928dccb561b2df6f5e5b4d09eab22cf67e8ff03
> Remove obsolete workaround.

- wrappers.lisp
As per #190, the logic of version check is wrong as it only checks for the patch number, and it wasn't working as intended since version 1.1.0, the successor for 1.0.58. The keyword argument is available since [1.0.24](http://sbcl.sourceforge.net/all-news.html#1.0.24), so IMHO we can safely assume the keyword argument :resolve-symlinks is supported.
> Removed version check from fix directory-no-deref on sbcl

- primitives.lisp
No need to use or/and when if does the same job
> get-frame-number-translation: Rewrite for clarity

- configure.ac
Doesn't really seem right for configure to bail out entirely if makeinfo isn't present, people can still build stumpwm itself which is all the majority of people want to do.
> Only issue a warning if makeinfo isn't present.

- floating-group.lisp
When a float-window has width or height equal to width or height of the screen, its last-width or last-height slot is not being properly updated when you go to the fullscreen mode.
So If you have, for example, a window with sizes 1280x720 on the screen with sizes 1280x1024, you will never return the window to normal size (and get BadValue error from x server).
Solution: remove unnecessary (as they seem to be) 'unless' conditions in accessor methods for window geometry slots.
> Fix fullscreen mode with floating windows

- window.lisp
This simple change allows me to type German Umlauts with `window-send-string`, after doing `setxkbmap de`.
> Allow non ascii chars to be typed in window-send-string.

- module.lisp
This typo wasn't noticed because `*module-dir*` is set by `make-image.lisp` to a proper value.  Also I added another commit to remove trailing whitespaces.  Is it OK?
> Fix default value of *module-dir*.

- stumpwm.texi.in
act-on-matching-windows was flagged, in stumpwm.texi.in, as a command
when it should have been flagged as a macro. This caused the manual
creation phase to fail, killing the whole build and stopping travis
tests. This patch fixes that.
> Fixed ccl build process

- events.lisp
Modified the focus-in event handler to ignore pointer focus-in
events. See issue #196 for a detailed explanation. It is possible that
this patch will also address the problems described in issues #187 and #94 .
> Do not process focus-in events of the pointer kind (fixes #196).

- user.lisp
If you run `show-window-properties` when there are no open windows, you get some debug from this function - this just handles that and shows a message instead.
> Handle show-window-properties error when no windows are open

- floating-group.lisp
- window.lisp
The behavior of *mouse-focus-policy* = :sloppy in floating groups is:
any window that gets the focus (e.g. by hovering over it with the
mouse) automatically raises. This is annoying and makes using floating
groups very difficult. This patch makes floating group windows grab
the focus but stay in the background.  Windows raise only when
clicked.
> Sane behavior of the sloppy mouse focus policy in floating groups.

- floating-group.lisp
- tile-window.lisp
- window.lisp
When invoke gmove-and-follow to a float group, an exception will
raised.  Because really-raise-window is defined for tile-window only.
Fix this via make it a generic function and provide method for
float-window too.
> Fix (gmove-and-follow "<float>") exception

- menu.lisp
I've made a few modifications to `menu.lisp`, so that the menu shows only the items matching all the regular expressions typed by the user (previously, the first matching item in the menu was highlighted, and that was it). Now it behaves a bit more like helm-mode for Emacs. It's been pretty useful, in particular with `pull-from-windowlist`.
The interface is exactly the same, so all other commands can take advantage of the new behavior with no further modifications. I've been using this stuff for a while now, and it hasn't shown any bug in the last few days.
Care to take a look?
(btw, this is the first time I've ever written anything in Common Lisp, any criticism/opinion is appreciated . Also, first time ever sending a PR, so, sorry if I'm not following quite the right procedure)
> Helm-like menu

- menu.lisp
- primitives.lisp
- tile-window.lisp
- window.lisp
This aims to solve #220.
The changes are, basically:
1. an additional argument to `select-from-menu` specifies a filter predicate, which is a function that says whether a given menu item should be visible or not, based on the user-visible string, the object corresponding to the item, and user input;
2. `select-window-from-menu` specifies a filter predicate that also checks the user-input regexp against the full window title (not just the portion shown in the menu).
It's also possible to override `select-window-from-menu`'s default by setting the `*window-menu-filter*` variable.
(I still consider myself a CL beginner; any criticism/opinion on the code or the general design is appreciated. Also: should I squash some commits?)
> Menu filter predicate

- bindings.lisp
- time.lisp
*time-format-string-default* is used for the version command.
Up to now the year was not included.
> time.lisp: *time-format-string-default*: Include the year

- events.lisp
- window.lisp
SDL-1.2 in fullscreen mode draws to a override-redirect window it
places covering the entire screen. However, it still creates a normal
wm-controlled window that it will not paint to, and if we take too
long between mapping that window and raising it, then it can wind up
hiding the intended fullscreen window.
Rather than attempt to guess which windows are non-painted SDL
windows, just grab the server for the entire map+raise section.
See #138
> Replace the fullscreen-SDL skip-raise heuristic with grabbing the server

- command.lisp
- tile-window.lisp
Hello, try this command:
```lisp
(defcommand bool-test (bool) ((:y-or-n ""))
(if bool
(echo "yes")
(echo "no")))
```
Now call it interactively and you always get "yes" message no matter if
you press `y` or `n`.
Alternatively, try this:
```lisp
(defcommand bool-test (bool) ((:y-or-n ""))
(echo bool))
```
It will display either `(T)` or `(NIL)`.  As you can see it wraps the
boolean value into a list. ``(define-stumpwm-type :y-or-n ...)`` does
this.  I also don't see a reason to use `values` and `when` there, or do
I miss anything?
> Fix "y-or-n" prompt

- primitives.lisp
The function is not called from anywhere else nor is it
exported. Furthermore PUSH accomplishes the same as CONC1
> Remove CONC1

- primitives.lisp
- stumpwm.lisp
It is called during both soft & hard restarts.
Addresses #265 
(This also cleans up some whitespace at the end of lines)
> Add *restart-hook*

- primitives.lisp
It'd probably be good were it exported as well as defined …
Sorry, I was in the STUMPWM package when testing.
> Export *RESTART-HOOK*

- ioloop.lisp
- stumpwm.lisp
- wrappers.lisp
I wanted to add more proper error-handling for I/O channels that cause errors, but the top-level condition handling was already quite complex, so I tried to clean it up a bit by moving its functionality to a generic function. Then I added I/O channel error handling.
One advantage of handling errors this way is also that new methods can be defined/redefined on HANDLE-TOP-LEVEL-CONDITION without having to restart the STUMPWM-INTERNAL-LOOP, making it easier to patch error-handling at runtime.
The resulting functionality should be similar to previously, but as I was at it, I did change so that non-warning, non-serious conditions are ignored, rather than handled as if they were errors. I would like to think that is the correct way of handling them, as they are likely to be "informational" …
> Top-level condition handling

- make-image.lisp.in
If true (the default on cheneygc), do a purifying gc which moves all dynamically allocated objects into static space. This takes somewhat longer than the normal gc which is otherwise done, but it’s only done once, and subsequent GC’s will be done less often and will take less time in the resulting core file. See the purify function. This parameter has no effect on platforms using the generational garbage collector[1].
[1] - http://www.sbcl.org/manual/
> add purify to image dump for sbcl.

- iresize.lisp
It was never used anywhere. The variable was introduced alongside the
initial implementation of iresize, in the commit https://github.com/stumpwm/stumpwm/commit/a71e89. It was
probably used for for debugging purposes.
> Remove *RESIZE-BACKUP*

- wrappers.lisp
SB-DEBUG:BACKTRACE has been deprecated in favor of PRINT-BACKTRACE since
SBCL version 1.2.15
> wrappers: Use PRINT-BACKTRACE instead of backtrace

- color.lisp
- message-window.lisp
- mode-line.lisp
Its use in the function was removed in #251. Remove it as it is no
longer necessary
> Remove unused screen argument from RENDER-STRINGS

- make-image.lisp.in
If a contrib module depends on the `stumpwm` system, ASDF will look for it in the build directory. When that directory no longer exists (which is fairly likely), loading of the module will fail.
By registering StumpWM and dependencies as ["immutable"](https://common-lisp.net/project/asdf/asdf.html#index-register_002dimmutable_002dsystem-1), we tell ASDF to treat the system as already loaded. It will not look for the system definition nor the source code again, unless you explicitly request it to be loaded.
Fixes stumpwm/stumpwm-contrib#17 (already marked as fixed, but not generally)
Fixes stumpwm/stumpwm-contrib#53
Some more testing would be appreciated.
> Register systems as immutable in a built image

- package.lisp
- stumpwm.asd
- stumpwm.lisp
- wrappers.lisp
This function allows a multi-threaded module to perform actions on the main
event handler thread and should be used whenever a different thread
needs to invoke any stumpwm functions.
Currently, only SBCL is supported.
> Implement CALL-IN-MAIN-THREAD

- window.lisp
When focusing some Java windows, like the IntelliJ app, window borders were not updated. I think this commit fixes that and I haven't noticed it causing any problems with other windows.
To test:
Without patch, move focus to IntelliJ window, notice that border doesn't update to show the window as selected.
With this patch, do the same thing, notice window border shows that it is selected.
> Fix window border updating on Java windows

- help.lisp
- primitives.lisp
This replaces: https://github.com/stumpwm/stumpwm-contrib/pull/58
I've attached a GIF demonstrating the behavior of `which-key-mode`
> Add which-key-mode

- window.lisp
fix grabbing wrong key when modifier is missing
fixes #296
> ensure a key's modifiers exist before grabbing it

- make-image.lisp.in
On ASDF versions prior to 3.15 we can't assume that the symbol
SYSTEM-DEPENDS-ON is exported in the ASDF package. If it is not present the
reader signals an error even though the code won't be executed.
As reported by user jmccabe on IRC. They were using SBCL 1.1.14 with ASDF 3.0.3 which are 3 years old on Linux Mint 17.
> Don't assume ASDF:SYSTEM-DEPENDS-ON exists

- events.lisp
Although more 'greedy' (it does more work than it needs to do) the code is more clear
> :ENTER-NOTIFY, Bind variables when introduced

- primitives.lisp
Although I can't reproduce the issue reported by [Dimitri](http://lists.nongnu.org/archive/html/stumpwm-devel/2017-01/msg00010.html), stump-tray loads fine and I have no issues using both packages at the same time, i.e.
```lisp
(defpackage #:foo
(:use #:cl #:stumpwm #:alexandria))
```
There is no reason why we should be exporting the flatten function anyway. I rgrep'ed through our contrib folder and found no uses of it so we should be save.
> Do not export FLATTEN symbol

- primitives.lisp
Currently *DEBUG-STREAM* points to the value that *ERROR-OUTPUT* has when the
code is loaded. And it is unaffected by any modifications to *error-output*. By
using a SYNONYM-STREAM, *DEBUG-STREAM* defaults to the value
that *ERROR-OUTPUT* is bound at the moment *DEBUG-STREAM* is referenced.
This [lisp-tip](http://lisptips.com/post/127524780849/when-a-synonym-stream-is-useful) explains the issue in further detail
> Use SYNONYM-STREAM for *DEBUG-STREAM*

- events.lisp
- wrappers.lisp
Remove support for other implementations other than SBCL. Use XLIB:WINDOW-ID
instead of accessing the direct slot of the DRAWABLE.
Moved the function to where it is used.
I would like to remove the function altogether but I have to investigate if the issue it is working around of (the cache returning a pixmap instead of a window) is still present in CLX.
> Move MAKE-XLIB-WINDOW out wrappers.lisp

- events.lisp
- wrappers.lisp
Following up on https://github.com/stumpwm/stumpwm/pull/318#issuecomment-275911342
<hr />
The issue it works around was fixed in CLX in the commit 86dea89f[0].
The following discussion[1] on sbcl-devel for further context.
[0]: https://github.com/sharplispers/clx/commit/86dea89fe6f1fee4720ed8d8fea34ea6c2e06d7b
[1]: https://sourceforge.net/p/sbcl/mailman/message/19823960/
> Remove MAKE-XLIB-WINDOW

- floating-group.lisp
- group.lisp
- window.lisp
The first commit fixes the issue that a group's current window would not actually be a window in that group. The issue has always been present in the floating group, but was recently also introduced in the tiling group when it gained the ability to contain floating windows.
The second commit allows focusing behavior to properly be managed by the group the window is in.
It introduces one possible change in behavior: The floating group's GROUP-FOCUS-WINDOW method now always raises the window. I am not sure this actually changes anything user-visible.
> Clean up current window tracking for groups

- group.lisp
- tile-group.lisp
- window.lisp
This PR is branched off https://github.com/stumpwm/stumpwm/pull/298
This allows one to display a float window on all groups. Combined with https://github.com/stumpwm/stumpwm/pull/302 should give some really nice support for floating windows. I watched lord of the rings using this functionality to create picture in picture viewer with Xephyr :) 
I considered adding support for always showing tile windows as well, but that is much more complex, and I'm not too sure that it's a very common use case at all.
> toggle-always-show for float windows

- tile-group.lisp
Currently `focus-last-frame` (used by `fother` command) calls
``(tile-group-last-frame group)`` 3 times!  I think it's not
good.
> Simplify 'focus-last-frame'

- bindings.lisp
`h` is left.
`l` is right.
```
h j k l
< v ^ >
```
> Fix vim like bindings left/right swap

- make-image.lisp.in
It's NIL on a current system, so this actually hard-sets SBCL_HOME to
NIL, which is not good.
SBCL_HOME doesn't appear to be required by ASDF anymore.
Fixes #332.
> Remove un-needed SBCL_HOME reference

- events.lisp
For some reason, XLIB:PROCESS-EVENT sometimes sends events for
drawables as well as for windows; this causes crashes later on.
Fixes #334.
> Only try to handle events with XLIB:WINDOW windows

- command.lisp
Change define-stumpwm-type :shell to allow the setting of the shell which the user wishes to run.
This is done by the addition of the variable *shell-to-use*.
When *shell-to-use* is nil the default "/bin/sh -c" is used otherwise the value of *shell-to-use* is used. 
Fixes issue #325
> Let shell to be run be set by user

- head.lisp
This is just a refactor or the current head implemenatation to make it more readable. It is a first stop towards #328, which seems to have gone cold
> Refactor make-screen-heads

- AUTHORS
- README.md
These are left behind from before the usage of non SBCL lisp implementations was removed so remove them.
> Remove non sbcl lisp implementation references from README

- README.md
- head.lisp
I've done some light testing with Xephyr, `Xephyr -screen 640x480 -screen 640x480 +xinerama :1 &`
> Use CLX's Xinerama extesion to query screen heads

- AUTHORS
- stumpwm.texi.in
- tile-group.lisp
So we can split a frame in n rows/columns of equal sizes.
I also reorganized the next command defined to fit in 80 columns, but I don't know if I'm breaking some style rule.
> Add more split functions

- module.lisp
When interacting with systems support is normally allowed to specify
the system by using a key instead of a string. Add this support to load-module.
> Allows keys to be used when loading modules

- window.lisp
Clisp bundles its version of clx which changed to using a list to
represent a windows flags instead of a integer.
Remove the workaround so we cold use both versions of clx as we now
only support one clx impementation.
> Remove clisp window urgency flags workaround

- floating-group.lisp
- group.lisp
- head.lisp
- tile-group.lisp
In the tiling group the pointer is usually ignored, but in the floating
group it is essential. Thus it makes sense to use its position to
determine the current head.
I think this makes sense, do you (@PuercoPop , @dbjergaard) agree?
> Find current head from pointer in floating group

- window.lisp
Clisp bundles its version of clx which changed to using a list to
represent a windows flags instead of a integer.
Remove the workaround so we cold use both versions of clx as we now
only support one clx impementation.
> window-urgent-p: Remove clisp flags workaround

- interactive-keymap.lisp
> doc(interactive-keymap): fix some docstring typos

- package.lisp
- stumpwm.lisp
The function `CALL-IN-MAIN-THREAD` checks whether the current thread is the main thread, in which case the function is called immediately. If not, an event is scheduled which will be called at a later time.
There are cases when one wants to schedule a function to be called from the event loop even if the executing thread is the event thread. A specific case for this is when calling the function `FLOAT-WINDOW` from a window create hook. `FLOAT-WINDOW` assumes that the window has already been placed, and if it's called directly from the hook, StumpWM will crash. Scheduling the call as an event using the new function `PUSH-EVENT` fixes this.
> Added functions IN-MAIN-THREAD-P and PUSH-EVENT

- selection.lisp
This commit ensures that any selection owned by stumpwm may be correctly requested by other X clients that use the `:targets` property request.
> Fix for incorrect selection targets property value

- floating-group.lisp
The & sigil is used to refer to lambda list keywords. It confuses Emacs's
syntax highlighting, which highlights calls to the function as lambda list
keywords even outside. Replace it with the more common idiom of using the % to
signal that it is an internal function that shouldn't be called directly.
> Rename &float-focus-next to %float-focus-next

- events.lisp
- primitives.lisp
Adds a `:selection-notify` event handler and `*selection-notify-hook*` to allow StumpWM to get clipboard (and other) selection from other X clients. Selection is saved in `*x-selection*`
The hook can be used to build useful utilities such as a `clipboard-history` module - an early draft (which depends on this hook) can be previewed [here](https://github.com/kriyative/stumpwm-contrib/commit/c25f6dfa887dd7f7ad1c18148592d76a6102d086).
> Feature selection notify hook

- events.lisp
The expansion of DEFINE-STUMP-EVENT-HANDLER would place any extra declarations
provided by the user of the macro below the always present (declare (ignore
,event-slots)) forsm. So any extra declare forms provided by the user of the
macro would be discarded as a there can only be one declare expression at the
start of the function body. Merge the user-provided declarations with the first
declare form.
> Handle user-provided declare forms correctly in event-handlers

- menu.lisp
- primitives.lisp
- stumpwm.texi.in
This lets the caller do something every time an item is selected.
A use case for this is is a "visual-pull-from-windowlist", which pulls
the selected window every time you select it. Here is an example
implementation that is currently used:
```common-lisp
(defcommand (visual-pull-from-windowlist tile-group) () ()
(flet ((pull-selected-window (menu)
(let ((selected-window (nth (menu-state-selected menu)
(menu-state-table menu))))
(pull-window (second selected-window)))))
(let ((original-window (current-window))
(pulled-window (select-window-from-menu
(group-windows (current-group))
*window-format*
nil
*window-menu-filter*
#'pull-selected-window)))
(pull-window (if pulled-window pulled-window original-window)))))
```
> Add a selection hook in select-from-menu.

- events.lisp
- primitives.lisp
- stumpwm.texi.in
So we can run stuff when a new monitor is plugged, for instance.
> Add new head hook

- stumpwm.lisp
I have $XDG_CONFIG_HOME set to $HOME/.config without the slash at the end (which is how it's defined in [the spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables)) so merge-pathnames would think .config is a file and elide it.
Adding a slash to the end would fix this behavior and still work even if the path already ends with a slash.
> Fix incorrect behavior when XDG_CONFIG_HOME doesn't end with /

- stumpwm.texi.in
Fixed a typo in the documentation for `*new-window-preferred-frame*`.
> Fixed documentation for *new-window-preferred-frame*

- color.lisp
- input.lisp
- message-window.lisp
- primitives.lisp
Currently only the horizontal padding can be changed throught the variable `STUMPWM:*MESSAGE-WINDOW-PADDING*`. This adds another variable, `STUMPWM:*MESSAGE-WINDOW-Y-PADDING*` to control the vertical padding.
I just wanted to do something very simple to learn how to contribute things. Let me know if I'm doing something wrong here.
> Allow user to change the vertical padding of message windows

- command.lisp
- stumpwm.texi.in
When using the `colon` command or stumpish to execute commands, there currently seems to be no way to enter strings with spaces as a single argument. In interactive use this isn't that big of a problem since you can enter the string in the separate prompt, but when controlling Stumpwm via stumpish it would be nice to be able to, for example, create a group with spaces in the name.
This changes the `ARGUMENT-POP` function so that it allows double quotes to be used as string delimiters. For example, with the `colon` command `gnew "foo bar"`will create a group named `foo bar`. Non-quoted arguments still work the same as before, so this shouldn't break anything.
> Allow double quotes as string delimiters for command arguments

- primitives.lisp
- time.lisp
https://github.com/stumpwm/stumpwm/issues/393
Unfortunately, I have not had time to test this yet, but it seems to compile fine and the changes are quite simple. If anyone can test that it runs as expected and there are no issues with the related time commands that would be awesome. 
I can confirm that using the `sb-posix:time` function fixes the system time change issue described in the bug report.
> create wrapper for getting decoded system time

- stumpwm.lisp
There reference was introduced in 89ff4d8, but no such class was present
in the commit 48a872e, that included the timers.lisp file.
> Remove reference to stumpwm-idle-timer-channel

- group.lisp
Kill other groups. All windows in other groups are migrated to the current group.
> Added the command "gkill-other".

- window.lisp
Kill all windows in current group except the current-window, as in this proposal https://github.com/stumpwm/stumpwm/pull/424#issuecomment-359135009.
> Add KILL-WINDOWS-OTHER command

- iresize.lisp
There is no problem when i call it within iresize, but error occur when i call `resize-direction` directly as command
> Solve error when calling `resize-direction` directly as command and add docstring to it

- AUTHORS
- module.lisp
Previously,` find-asd-file `could return files that contained "asd" in its name. This caused backup files or other unwanted files to be returned, which in turn caused some modules to not be found. This pull request makes `find-asd-file` check the full file extension before returning.
> find-asd-file now only loads files with .asd extensions

- module.lisp
Previously the check only checked if asd was contained in the entire
filename. Change this to only check the file type by splitting out the
type from the file before performing the check.
> Fix checking if a directory contains a .asd file when loading modules

- events.lisp
This PR adds a dynamic var binding of the current key sequence before invoking any command bound to that key sequence. This feature supports the [REMAP-KEYS](https://github.com/kriyative/stumpwm-contrib/commit/6acf68de83a3e439106b592cd56fd39d23643de6) module.
> Bind current key sequence in dyn var ahead of calling a command

- remap-keys.lisp
I updated StumpWM and decided to try out the new key remapping stuff.  I ran into some really tricky bugs and hangs that I finally tracked down to some bad uses of `MAPCAN`. 
`MAPCAN` destructively modifies the lists to concatenate them together.  This is a problem because it changes the value of `*remap-keys-window-class-list*`, which results in incorrect functionality and totally breaks the unmapping process.
Example:
(define-remapped-keys
'(("Firefox"
("C-n" "down")
("C-p" "up"))
("xterm"
("s-c" "C-C")
("s-v" "C-V"))))
This attempts to add two remappings for Firefox and two for xterm. After the initial `setq` in `define-remapped-keys`, `*remap-keys-window-class-list*` looks something like this:
(("Firefox"
("C-n" #S(KEY down))
("C-p" #S(KEY up)))
("xterm"
("s-c" #S(KEY ctrl-shift-c)) …
> Fix key remapping by not using `MAPCAN`

- bindings.lisp
- floating-group.lisp
- kmap.lisp
In #480 I was confused because the documentation strongly implies that `*root-map*` is what you see when you type the prefix key. But actually what you see is a concatenation of `*root-map*` and `*group-root-map*` and (`*tile-group-root-map*`|`*float-group-root-map*`). This was frustrating because I was trying to throw away the entire prefix menu by altering `*root-map*`.
Probably, I would not have found this info even if the variables were documented because I was reading https://stumpwm.github.io/git/stumpwm-git.html
Still, hopefully this PR is more helpful than not.
> Add documentation of the other '-root-map*' vars

- stumpwm-tests.asd
- stumpwm.asd
- tests/kmap.lisp
- tests/package.lisp
Also setup the necessary machinery to run the tests through ASDF's
test-op:
(asdf:test-system "stumpwm")
While trying to rewrite parse-key I kept running into edge-cases. I've added some happy path examples as well as some edge cases to test parse-key to get a test suite going.
Something I'm unsure of, although it makes sense conceptually for the test-op to be on StumpWM, as it currently stands every time we change a file on StumpWM the test-op will recompile the system before running the tests, which are not immediate.
Let me know what you think
Ref. #453
> Add tests for PARSE-KEY

- bindings.lisp
- fdump.lisp
- stumpwm.texi.in
- window-placement.lisp
I sometimes move windows to different groups.
The new command place-current-window re-places the current window according to the placement rules
> Add new command place-current-window

- AUTHORS
- primitives.lisp
- tile-group.lisp
I would like the mouse to follow all folder splits and removals so the mouse stays inside the frame.  To do this I've added a hook so that the mouse can be repositioned when a frame is removed.
Example config code I use to get this functionality:
```common-lisp
;; :click, :ignore, :sloppy
(setf *mouse-focus-policy* :sloppy)
(defun temporarilly-disable-sloppy-pointer ()
"Disable the sloppy pointer for a brief period of time."
(when (eq *mouse-focus-policy* :sloppy)
(setf *mouse-focus-policy* :ignore)
(run-with-timer 0.2 nil #'reenable-sloppy-pointer)))
(defun reenable-sloppy-pointer ()
(setf *mouse-focus-policy* :sloppy))
(defun mouse-inside-frame-p (frame)
"Determine if mouse already inside frame."
(multiple-value-bind (mouse-x mouse-y window)
(xlib:global-pointer-position  *display*) …
```
>  Add *remove-split-hook* 

- group.lisp
Exactly what the commit message says. This fixes a cosmetic error that occurs when the user exits an interactive call to `gnew`.
> Command 'gnew' no longer shows error when exited with C-g

- kmap.lisp
In 38d19ca7ea93fa9ff991ffd83735e78828a71b83, KBD-PARSE was renamed to
KBD-PARSE-ERROR, but one usage was left unchanged. This fixes that.
Additionally, PARSE-KEY and PARSE-MODS would use SIGNAL to signal the error.
This would obscure such errors when called from the REPL, since the condition
would reach top level. This changes those calls to use ERROR instead.
This is a simple replacement for #479 that fixes #497. It is probably not a full solution to #484.
> Fix PARSE-KEY to error with KBD-PARSE-ERROR

- message-window.lisp
- stumpwm.texi.in
add `with-message-queueing` macro:
Queue all messages sent by (MESSAGE ...), (ECHO-STRING ...), (ECHO-STRING-LIST ...) forms within BODY without clobbering earlier messages. When NEW-ON-BOTTOM-P is non-nil, new messages are queued at the bottom.
See #499
> add with-message-queuing macro

- events.lisp
+ may be worth checking if the issues mentioned in #502 are still present in `clx` that were fixed in 
commit 9061ec2ba3bf72b38848ebf8821da8ca5c51d0ee, which is where this code originated.
> Change xlib::make-window to equivalent `make-instance` call

- group.lisp
Removes one of the warnings mentioned in #504
> Move definition of group class to avoid warnings

- dynamic-window.lisp
The argument is defined so that user-provided hooks can play with it,
but the default function does not use it, so we can declare it as
ignored to remove the style-warning during compilation.
> Fix style-warning.

- mode-line.lisp
- primitives.lisp
- timers.lisp
Various mode-line functions and timer functions are used before the
struct is declared, which means the functions were already compiled,
and they thus can't be inlined.
SBCL gives this warning:
; caught STYLE-WARNING:
;   Previously compiled calls to STUMPWM::MODE-LINE-SCREEN,
;   STUMPWM::MODE-LINE-POSITION, STUMPWM::MODE-LINE-HEIGHT,
;   STUMPWM::MODE-LINE-FACTOR and STUMPWM::MODE-LINE-MODE could not be inlined
;   because the structure definition for STUMPWM::MODE-LINE was not yet seen. To
;   avoid this warning, DEFSTRUCT should precede references to the affected
;   functions, or they must be declared locally notinline at each call site.
Which this commit fixes by moving the struct declarations earlier.
It also probably gives a very tiny bit of better performance.
> Declare mode-line and timer before using them.

- input.lisp
- stumpwm.texi.in
- tile-group.lisp
Follow-up of https://github.com/stumpwm/stumpwm/issues/509
This essentially requires the creation of `read-one-char-or-click`, which listens for both "one char" or "click" events together, and returns the appropriate information to `choose-frame-by-number`.
Note: it makes `expose` much more pleasant.
> Make fselect frames clickable.

- NEWS
Looks like this was leftover from a merge conflict.
> NEWS: remove merge cruft

- primitives.lisp
Using the &BODY lambda list keyword instead of &REST hints the CL IDE to
indent to declare FRAME-RULES using the same offset. Using &rest the
indentation would be as follows
```lisp
(define-frame-preference "Shareland"
(0  t 0 :calss "XTerm")
(1  0 t :class "aMule"))
```
Using &BODY the alignment is
```lisp
(define-frame-preference "Shareland"
(0  t 0 :calss "XTerm")
(1  0 t :class "aMule"))
```
> D-F-P: Use the same indentation for all the FRAME-RULES

- events.lisp
As LOGIOR is the equivalent of C's bitwise or (||) it communicates the
intent of the operation better.
> BYTES-TO-WINDOW: Use LOGIOR instead +

- tile-group.lisp
- GROUP-BUTTON-PRESS: Use WHEN-LET
- Refactor FIND-FRAME
The WHEN had not body, instead we depended on the short-circuiting
behaviour of AND. Move the RETURN form to the body of the WHEN. The <=
is varidic in CL, we can merge both comparisons for y/x into one call to
<=.
I'm leaning towards leaving the WHEN because it is explicity about what
are the preconditions and what is the consequent. If we opt to eliminate
the WHEN form, sacrificing explicitness we would have more compact code:
(and
(<= fy y fhy)
(<= fx x fwx)
(return f))
> Misc fixes

- AUTHORS
- message-window.lisp
- primitives.lisp
- stumpwm.texi.in
The same gravity setting was being used for both the message window
and the input window, making displaying both at once problematic.
Added special variable *message-window-input-gravity*
that is to be used as a message window's gravity
when the input window is being displayed so that they do not overlap.
The function message-window-real-gravity should be used to compute
the proper gravity to use when displaying a message window.
> Message window input gravity (split from https://github.com/stumpwm/stumpwm/pull/517)

- window.lisp
Before commit 3e3ce5b this was not necessary as ESCAPE-CARET defaulted
to the empty string when passed NIL.
Closes #524
Co-authored-by: Javier Olaechea <pirata@gmail.com>
> Make explicit that "" is the default value of XWIN-NAME

- events.lisp
- remap-keys.lisp
- stumpwm.texi.in
- window.lisp
- Revamps the remap-keys implementation by introducing a new `*custom-key-event-handler*` in events.lisp
- Reverts a previous commit, which was the cause of issue #494 
- Adds support for functions which can be used to switch remap-keys based on different properties of the focused window
> Fix remap-keys related issues

- floating-group.lisp
- Avoid type-error by checking ml before retrieving ml-height in
window-display-height and maximize-float function.
- Adding default 0 for ml-height and remove checking :hidden mode for
ml before calculating maximum displayable height.
- Calculating width and height must involve \*normal-border-width\*,
\*float-window-border\* and \*float-window-title-height\*.
> Fix double click behavior on float window title.

- events.lisp
Previously, when a window in a tiling group was made to float, then
unmapped and then mapped again, StumpWM would crash. The tile-group
method for group-raise-request calls maybe-map-window, and
maybe-map-window assumed its argument was a tile-window.
The crash is easy to reproduce using Inkscape:
1. Start Inkscape
2. Press `C-P` to open the preferences
3. Use the command `float-this` to make the preferences window float
4. Use the command `delete` (`C-t k`) to close the window
5. Press `C-P` again
> Fix float window map request crash in tile group

- input.lisp
This way `all-modifier-codes` is oblivious what to how many values or in which order `xlib:modifier-mapping` returns.
> Simplify the implementation of ALL-MODIFIER-CODES

- stumpwm.texi.in
adds an example of overriding the default exit keys in define-interactive-keymap which adds SPC to the exit commands. It could also be rewritten without the defparameter, but i found it more readable this way.
> add :exit-on example for define-interactive-keymap

- floating-group.lisp
___
After I change config to distinct border like this:
```
(setf *normal-border-width* 4
*transient-border-width* 3
*float-window-border* 5
*float-window-title-height* 10)
```
I realize i made mistake with counting windows geometry. Here is what I got:
- It seem \*normal-border-width\* only showed on float-window and not selected tile-window
- frame-height != window-height, it's involve \*normal-border-width\*
- frame-height not always same with window-height  plus 2  \*normal-border-width\*
- geometry-hints always helpful to work with tile-windows
With that discovery I changed the float-window-align and set the geometry so that when adding borders, it won't change the size of the window. Although it change the width and height of slot from window because of addition borders.
___
Set …
> Border calculation on float-window

- events.lisp
- head.lisp
Xinerama has several drawbacks, including that it doesn't support
dynamic reconfiguration of monitors by default (e.g. the list of
numbers is random).
Using RandR API, we notably gain the ability to get the EDID of the
monitors, which means we'll be able to store where frames were between
monitors plugs and restore them when it makes sense, for example.
Given that older machines might not support RandR (it's fairly
"young"), Xinerama support is still left in the existing
implementation.
PS: I also sneak in a trailing whitespace removal, sorry :stuck_out_tongue:
> Generate the heads using Xrandr instead of Xinerama.

- menu-definitions.lisp
The `table` argument to `select-from-menu` uses a nested list, not an alist. See issue #564 for more details.
> Update select-from-menu documentation to reflect reality

- events.lisp
- head.lisp
- primitives.lisp
The documented `*new-head-hook*` has a couple of issues:
- The first one, reported in #567, is that the hook is not exported, despite being present in the documentation.
- The second one is that it wouldn't run for a manual `refresh-heads` command, which is unfortunately needed quite often in my limited experience when plugging/unplugging monitors. Note that the proposed fix has a small BC break: the hook is now run before `(update-mode-lines)` instead of after.
> Fixes for *new-head-hook*

- head.lisp
- primitives.lisp
It turns out that the EDID property returned by CLX is not unique at
all.
To fix this bug, we fallback to the previous behavior of using a
simple counter to assign the head number.
That said, because it can be useful later on, a new NAME property is
added to the head struct. _That_ property is unique, but turning it
into a number requires hashing it, which we might want to avoid as a
first step. (So, right now, it is only useful for introspection purposes.)
> head: use normal counters for xrandr heads.

- primitives.lisp
- user.lisp
This PR addresses #343 
The code is simple enough. Add the ability for hooks to be disabled, and disable them when drawing a restarts menu.
This is not necessarily the final way to solve this issue. Perhaps there is a way to still run all the hooks and ensure stumpwm doesn't crash if an error occurs. I'm open to suggestions!
> Don't crash when error happens in *message-hook*

- events.lisp
- floating-group.lisp
- group.lisp
- tile-group.lisp
I don't have any lag on my system to actually check if this fixes #252, but I can confirm that the modeline no longer updates on each scroll event. Even if we go with the solution written by @ralt in #577, the first commit in this series should probably stick around.
> Don't update the modeline on mouse scroll events

- mode-line.lisp
- primitives.lisp
- stumpwm.texi.in
Essentially, instead of redrawing the mode-line every time it is asked
to, a new thread is spawned for each mode-line, and that thread
redraws the mode-line every *mode-line-refresh-interval* (every 200ms
by default).
In practice, 200ms is not noticeable by the human eye. If you have
great eyes, it is very easy to reduce the interval.
Testing with this change, and the following mode-line:
```
(ql:quickload :local-time)
(defun get-date-modeline ()
(local-time:format-timestring
nil
(local-time:now)
:format '(:short-weekday #\space :short-month #\space
(:day 2 #\space) #\space (:hour 2) #\: (:min 2)
#\: (:sec 2))))
(setf *screen-mode-line-format*
(list "^n^b %g ^n^b %W ^> "
"  "
"^n^b%B "
'(:eval (get-date-modeline))))
```
I now have:
- The Slack web application no longer lags when …
> Make the mode-line faster and less intrusive.

- screen.lisp
It avoids the bug where the default background being :none means that
switching to a new group means having an overlay of the previous
group.
Fixes #94
> Set a default background color on the root window of every screen.

- interactive-keymap.lisp
- stumpwm.texi.in
This adds the command call-and-exit-kmap, which allows us to run a command, and then run the exit command for the appropriate interactive keymap. It also modifies define-interactive-keymap so one can specify specific bindings that exit the keymap when run, by virtue of passing them to call-and-exit-kmap. This action is triggered by appending any true value to the end of the key binding. 
in the below example, pressing 'n' will run 'meta n', while pressing m will run 'meta x' and then exit the interactive keymap. 
(define-interactive-keymap example ()
((kbd "n") "meta N")
((kbd "m") "meta x" t))
this modification of define-interactive-keymap preserves the original usage, and doesnt break existing code using it.
> exit keymap via specific bindings.

- input.lisp
This patch allows detecting that ```ISO_Level3_Shift``` is ```mod5``` on my machine.
I needed another modification to make the AltGr-key combinations return the right symbols: replacing ```(base (if altgr-p 2 0))``` by ```(base (if altgr-p 4 0))``` in the ```code-state->key``` function.
However I didn't put it in this pull request, as I have no idea if 4 is the right value for all mappings or if there is a way to detect/compute what the right value for ```base``` is.
For information, I'm running XFCE 4 as desktop manager with stumpwm instead of xfwm4 as window manager, with a french keyboard layout.
> Improve search of modifier keys in get-modifier-map

- configure.ac
- make-image.lisp.in
This patch will only have an effect if SBCL was compiled with compression support enabled.
On my system, with this patch, the size of the produced *stumpwm* binary decreases form 57 MB to 15 MB.
> Activate compression of executable file

- tile-group.lisp
Closes #600.
Also relevant is #597.
This reduces the number of surprising focus situations, especially for new users, and I don't think there's much of a use for the old behavior.
> Focus on click with sloppy mouse focus policy

- keysyms.lisp
Hello, I noticed that my laptop has a key that was not defined by StumpWM.  I found its name (`XF86RFKill`) and keysym with `xev`.
I thought that it is probably not the only key missing in stumpwm, so I tried to find keysyms of other keys, but I quickly gave up.  All these keysyms and keycodes is a black magic for me.  The only source of `XF86RFKill` key I could find is:
https://cgit.freedesktop.org/xkeyboard-config/commit/?id=39927132729bcd8569716f4ccd3a2e3eadfaf186
And I have no idea how it relates to the hexadecimal keysym value I got from `xev` :blush:
Anyway, I hope adding just one new key is better then nothing.
> Add keysym for XF86RFKill

- window.lisp
Before this commit stumpwm send a :configuration-notify event to the
managed xwindow that doesn't take in account the border of the
xwindow, but only the position of the parent xwindow.
This is particular important for float windows where the border is not
zero by default and there is a high top border for title.
This fix issue #613
> Fix :configuration-notify event

- AUTHORS
- remap-keys.lisp
- stumpwm.texi.in
As a former EXWM user I really appreciated the feature to disable
remapping of keys temporarily. As far as I know stumpwm provides
`send-raw-key` to temporarily ignore remapping for a single key.
This pull request introduces a toggle behavior to temporarily disable
remapped-keys for more than a single key
```lisp
(defun remap-keys-allow (win)
(every (lambda(w) (string-not-equal w (window-class win)))
'(list "jetbrains-idea"
"Emacs"
"jetbrains-pycharm"
"jetbrains-studio"
"android-studio2")))
(define-remapped-keys
`((,(lambda (win) (remap-keys-allow win))
("C-a"   . "Home")
("C-e"   . "End")
("C-n"   . "Down")
("C-p"   . "Up")
("C-f"   . "Right")
("C-b"   . "Left")
("M-b"   . "C-Left")
("M-f"   . "C-Right")
("M-v"   . "Prior") 
("M-w"   . "C-c")
("C-w"   . "C-x")
("C-y"   . "C-v")
("C-_" …
```
> introduce toggle for remapped-keys

- screen.lisp
The default font is set to be `9x15`. If that font can't be found, StumpWM gets a list of all fonts and picks the first one. Choosing the fist font is rarely the right thing to do, and a better default is to use `fixed`.
This change updates StumpWM to choose `fixed` in this case, and only reverts back to the first available font if it `fixed` cannot be found (which should be a very unlikely scenario).
> Improve default font selection

- tile-window.lisp
In some cases, an off by one error caused the frame width to be negative,
resulting in a crash in CLX
> Fix a crash when splitting windows in some specific cases

- Makefile.in
OpenBSD has old makeinfo as part of base system which errors in stumpwm info
generation. This allows to override the makeinfo command so that later version from the OpenBSD ports tree can be used instead (gmakeinfo).
> allow overriding of makeinfo command

- window.lisp
The remap-keys functionality allows separate key mappings for different
windows by regrabbing the keys in a focus-window-hook every time the
window focus changes:
https://github.com/stumpwm/stumpwm/blob/5e1abc5c6ab4db051c058f83487b72b385814707/remap-keys.lisp#L66-L69
Separately: when a :mapping-notify event arrives, all key mappings are
resynced with sync-keys, which ungrabs everything and regrabs the keys
Stump cares about:
https://github.com/stumpwm/stumpwm/blob/5e1abc5c6ab4db051c058f83487b72b385814707/events.lisp#L380-L385
This means that if a :mapping-notify event arrives, any keys remapped
with remap-keys will no longer work until you unfocus and refocus the
window, which is annoying.  This patch makes sync-keys also run
remap-keys-grab-keys to restore those mappings.
The reason I …
> Regrab remapped keys when syncing keys

- events.lisp
- user.lisp
- wrappers.lisp
This is a first step towards avoiding the coercion at the beginning of `utf8-to-string`.
> Minor cleanups

- selection.lisp
This PR fixes an issue where StumpWM tries exporting X selection text with extended characters as simple strings, which causes CLX to raise an exception. The fix is to canonicalize selection text into UTF8 octets before exporting.
Related to issue #656
> Fix export selection as utf8

- tile-group.lisp
Presently FRAME-RAISE-WINDOW with W as NIL is hiding FRAME-WINDOW's in wrong
order where active focused window hidden first then its previous and so on which
put active focused window in between, rather than on head So after running
FCLEAR when PULL-OTHER-HIDDEN-WINDOW called it is not pull last active focused
window.
> FRAME-RAISE-WINDOW with W as NIL HIDE-WINDOW in their access order

- head.lisp
> Adds a config to conditionally enable RANDR in make-screen-heads

- bindings.lisp
- stumpwm.texi.in
This very useful and pretty command that provides a quick mechanism for
jumping windows is bound by default.
> Bind and document "expose" to C-t RET and C-t C-RET

- command.lisp
- stumpwm.texi.in
- user.lisp
Meant to address https://github.com/stumpwm/stumpwm/issues/501, where the goal is to shunt all these "miscellaneous" things into useful sections. What I've done:
- Add as few sections as possible, but do so where necessary
- Add "Advanced Configuration" section for things that are too esoteric to go in the Introduction, but are useful for configuration purposes.
- Fix any obvious documentation-related problems I come across as I do this (typos in docstrings, document undocumented things, comments where docstrings belong, etc.).
- No uncategorized items.
> Documentation: Miscellaneous items, Advanced Configuration.

- stumpwm.texi.in
Document ###, %%%, etc. in the manual.
From https://github.com/stumpwm/stumpwm/pull/682
but only the documentation for what is currently in the master branch at https://github.com/stumpwm/stumpwm/commit/32f5ccd85043d14ca05a6d80e8a48d768fd3de8b
So like https://github.com/stumpwm/stumpwm/pull/682
but does not document `+++` or `&&&`.
> Document how the manual is generated and how to add line item macros

- Makefile.in
- configure.ac
Only build the manuals if makeinfo is available when
`./autogen.sh && ./configure`
is ran. Previously the build would fail.
Fixes #648
> Do not require makeinfo to build successfully

- dynamic-window.lisp
- stumpwm.texi.in
- tile-group.lisp
`expose` made two unconditional calls to the "only" command, which results in
spurious messages "There's only one frame." Also, it called "fselect" on only
one frame, forcing the user to select the only frame.
The new function `only-one-frame-p` is defined and wraps these to ensure the user
is only shown `fselect` or the error messages from `only` when it makes sense.
Fixes the bug in issue #687
> Don't expose with only one application or only one frame

- AUTHORS
- help.lisp
- stumpwm.asd
- stumpwm.texi.in
Try: C-t h k C-i ? which will pop out: 
"? shows the bindings for the prefix map under C-t."
Previously describing a key would only show what command it ran, but now it provides the docstring also:
https://drive.google.com/file/d/1ibdQmd2BXBThWqPAhh_-SXNc5AjHo-rQ/view
> Make describe-key show more helpful information

- bindings.lisp
- user.lisp
(sb-ext:exit) provides a sure-fire way to quit everything on SBCL.
Running `C-t : quit` only closes the mode line, but does not totally close everything. Also, adding the keybinding `C-t q` is helpful, since many users of StumpWM cannot use it as their only window manager yet. Since it is easy to accidentally hit it (thereby closing all your windows and possibly losing a lot of work) it asks a one-character prompt: `Really close StumpWM? (y or n)`.
> Add quit keybinding, ask to quit, and use sb-ext on SBCL (#675)

- selection.lisp
- stumpwm.texi.in
One may desire to use the `clipboard` instead of the `primary` selection, or even clobber both.
Addresses https://github.com/stumpwm/stumpwm/issues/673
> Make get-x-selection and set-x-selection have configuration choices for clipboard vs. primary selections #673

- README.md
I noticed a few issues with the README, so I made these minor edits.
* stumpwm -> StumpWM.
* emacs -> Emacs.
* Use semicolons instead of commas to separate two independent clauses.
* sloc -> lines (less jargon, same meaning).
* use `./autogen.sh` to configure. Currently it just runs `autoconf`,
but that should not be expeceted.
* comment on the issue #666
* Note that the default path is not `/usr/bin/stumpwm` but
`/usr/local/bin/stumpwm`
unless a prefix arg is used for make.
* Remove the self-fulfilling prophecy "our wiki is in disrepair".
Trashing the wiki is not a good way to encourage contribution.
* Make the IRC channel bold (it is a common convention to emphasize
channels within surrounding text).
* Put the `C-t h *` commands in a pretty table.
> Edit README for correctness

- command.lisp
Fuzzy regex completion here is superior to invisible completing read.
Addresses #690
[Screenshot of this thing in action](https://spensertruex.com/static/fuzzy-colon.png).
I'd like to show the lambda-lists of these, and to make them less emphasized than the name (since completion should only be on the command name, not the lambda-list). [The second line in this screenshot of the new describe-key shows the how I'd like it to be](https://spensertruex.com/static/describe-command-short.png). But that is a much bigger change to the UI than just adding completion
> Make colon have pretty select-from-menu regex completion

- menu-definitions.lisp
The docstring says that a list like `'("here" "are" "completions")` should work,
but it only worked with `'(("here") ("are") ("completions"))`.
Modifies the `check-type` declaration to reflect this, and calls `mapcar #'list table` as needed.
> Makeselect-from-menu accept a list of strings

- command.lisp
- group.lisp
- stumpwm.texi.in
Fix these bugs. `gselect` had to be refactored a bit, since it still needs to support numerical arguments (but call `grouplist` otherwise`).
A couple sections of the manual were duplicated in the last few merges somewhere. This causes the build to fail.
`describe-command` had a bug where `("command")` was being returned from `select-from-menu` without being `car`'d into `"command"`.
> Bugfix merges: describe-command, manual section duplication, gselect

- user.lisp
The rationale is that it could be *really bad* to quit accidentally.
Modeled on the `gkill` color scheme when closing a non-empty group. [Here is an image of this prompt](https://spensertruex.com/static/really-quit-or-die.png).
I'm against flashy colours in most cases, but this one is special.
> Use color to emphasise the confirm-quit prompt

- fdump.lisp
- group.lisp
- help.lisp
- input.lisp
- interactive-keymap.lisp
- remap-keys.lisp
- stumpwm.lisp
- tile-window.lisp
- user.lisp
- window.lisp
* Message should end in a period, just like the ANSI spec for errors.
* Also should not end in a fresh line.
* When prompting for user input a colon is best.
Just trying to improve the consistency of the UI. I'd also be happy if none of them had periods, so long as it was consistent. I wouldn't want to be distracted by said inconsistency.
> Make messages punctuation more uniform

- command.lisp
- help.lisp
Remove extra spaces, and extra colon ':' from describe-key.
> Debug prompts for describe-* commands

- manual.lisp
Remove `dprint` https://github.com/stumpwm/stumpwm/pull/684
It is usually possible to figure out the error based on the error message anyway.
> Remove dprint commented-out function.

- command.lisp
Resolves #713
Reverts the regex completion system to input line. The old commit was 41f0f70.
> Revert colon to use completing-read instead of select-from-menu

- command.lisp
- help.lisp
- stumpwm.texi.in
* Using SBCL's `describe` for this purpose has some problems, and is much uglier than this. For example, it is possible to color the function/variable names, control width and height, remove unhelpful information (for a StumpWM user) and add an elipsis to the current value if it is too large.
* describe-var shows the value of the variable, but limits it to `*help-max-height*` lines, when it makes an elipsis (see screenshot).
Mandatory screenshots:
- [describe-function](https://spensertruex.com/static/describe-function.png)
- [describe-variable](https://spensertruex.com/static/describe-variable.png)
> Improve describe-function and variable with pretty emacs-like output

- group.lisp
- tile-group.lisp
This is intended to provide some feedback for commands that silently do nothing in exceptional situations. This kind of thing can be done in a lot of ways, but the standard way in StumpWM is to display a very short message.
Try these commands:
- With only one group (probably `Default`). `gnext`. Sends message `No other group.`
- `gkill` your new group. Messages now have periods, and `Deleted` is now `Deleted GROUP-NAME.`.
- `gkill-other` also has the messages `No other groups.` and `Killed other groups.`
- Open an application, focus it, and run `gmove`. Select the current group (ie. "move" it to the current group). The new message `That window is already in the group GROUP-NAME.` is shown. Previously this silently did nothing.
- Run `only`, then `fnext`. The new message `No other frames.` …
> Add feedback messages to groups and frames

- tile-group.lisp
As per documentation `only-one-frame-p` verifies if the **current head** has a single frame. `focus-frame-after` also works with multiple heads, so [this change](https://github.com/stumpwm/stumpwm/commit/29d4490f3a84f6e7cac96df5c11600e4d9645893#diff-4576d6a1869074a91fd1368f290a9279R1134) breaks frame switching on multi-head setups (where there can be one frame maximized on one head, yet there being multiple frames in total). I'm not sure if my proposed change shows the message as intended, because I only have multi-head setups where there are always multiple frames in total. Could someone please try if this is a suitable replacement for the original change? Thanks!
> Fix frame switching for multi-head setups

- group.lisp
GSELECT command doesn't accept a group as argument. So
GMOVE-AND-FOLLOW needs to call SWITCH-TO-GROUP function.
Fix #731
> Fix bug in GMOVE-AND-FOLLOW command

- input.lisp
Read-one-line would lose focus, making it impossible to close. Was especially a problem with the pinentry contrib: https://github.com/stumpwm/stumpwm-contrib/issues/165.
> Fix read-one-line loss of focus.

- input.lisp
Just a QOL change to remove duplicates from the completion pane. I do remove-duplicates *after* limiting the completion size due to performance being visibly effected if I do it before.
> Remove duplicates in the completion pane

- input.lisp
This patch does two (possibly controversial) things:
1. Suppress showing *all* possible completions when the user hasn't typed anything at all yet.
2. If the completion list is truncated to fit `*maximum-completions*`, replace the last completion with `... and N more`.
I added item 1 is because I find it very disconcerting to immediately have a giant list of words immediately thrown at me when I open a prompt.  It *is* cut down to fit `*maximum-completions*`, but that means what I end up seeing is the first N alphabetical items every single time, which doesn't seem super helpful.  This patch delays showing the list of completions until the user has at least typed *something*.
I added item 2 because if I get a list of completions that looks roughly like it's around the maximum length I've …
> Suppress displaying completions of "" and note truncated completion list

- help.lisp
Since commit afe8d38 _describe-key_ fails for a key that is bound to a command with arguments.
Example: `C-t h k C-t F1` gives the error message
_Error In Command 'describe-key': The value
NIL
is not of type
STUMPWM::COMMAND_
This patch restores the old message (binding with arguments) and adds the details introduced by commit afe8d38 for the underlying command:
_C-t F1 is bound to "gselect 1".
"gselect" is on C-t g quoteright.
GSELECT &OPTIONAL TO-GROUP
Accepts numbers to select a group, otherwise grouplist selects._
> Bugfix: describe-key for binding with args

- primitives.lisp
Hi, I was reading the doc and a found a weird sentence.
So, here's a pull request.
> fix echo-timeout*'s docstring's syntax

- command.lisp
- input.lisp
This request adds Emacs style completion to the colon command. I'm unsure if this is wanted, but I figured that since StumpWM and Emacs are so similar it might be. The new behavior of colon changes SPC to insert either a hyphen or a space, depending on whether the current input line either 
A) can be expanded into a command (in which case it is)
or 
B) contains a space (because it has already expanded a command)
It also changes RET to expand an input line if applicable and then return `:done`, as well as M-SPC to insert a space. 
once a line is submitted, the keys are rebound back to their original bindings to prevent this behavior when not inputting a command. 
Does this seem like something the community would like? I've attached a picture of it in use, to clear up any misunderstandings …
> Add Emacs-esq completion when inputing commands via colon

- primitives.lisp
As far as I can tell, `split-seq` is never actually called with a nil argument currently, but the code at the moment will completely ignore `nil` as a separator due to using `find`, which is an undocumented potential footgun.
> Make SPLIT-SEQ work with a nil separator

- user.lisp
Previously the prompt would stay up indefinitely until some action cleared it
incidentally.
Press any character or key combination other than `y` to close the prompt.
> Hide quit-confirm prompt when aborted or 'y' is not entered

- help.lisp
Fix NIL docstrings and missing spaces in WM messages, add completion
NIL docstrings do not show up in messages anymore, since they return "" instead.
This makes for less noisy descriptions.
The prompt messages for describe-function and describe-command now have a space
after the colon. This makes them consistent with the other prompts, and I think
it is cleaner.
Where-is command has completion just like describe-command, which makes it
easier to use.
> Documentation commands debugging

- fdump.lisp
- stumpwm.lisp
Use UIOP's `XDG_*_*` functions where needed, and save file dumps in the `XDG_DATA_HOME` with a `.dump` file ending.
Previously the dumps were saved in the home directory. This new way is better because it does not dirty the home directory, and it opens the door for listing all the available dumps in the directory to choose from when restoring.
Resolves https://github.com/stumpwm/stumpwm/issues/746
> Dump/restore configurations on XDG base dir file locations

- help.lisp
This builds on the following PR: #750 which is tagged 19.11-doc-v1
whereas this PR is tagged 19.11-doc-v2
Where-is is made more useful by showing aliased names and keys
Displays the aliases to a command, even if it is not itself bound to any keys.
This makes for a much more useful where-is message for tracking down the
relationship between a particular action and a key.
This makes for a more verbose message, but in my experience I usually wanted
that extra information, since that is why I did a where-is in the first place.
In most cases it makes no difference (since most commands are not aliased), and
it normally just adds a few lines, and the messages are still small and
non-obtrusive.
> Where-is alias keybindings support

- mode-line.lisp
This fixes an issue where the mode line will appear above full-screen windows in some circumstances. A way to trigger the bug is to have a window already open, then enable the mode line; if that window is made full-screen, the mode line will appear over top of the full-screen window.
> Keep mode line below other windows

- stumpwm.texi.in
`dump-to-file` and `restore-from-file` write to XDG_CONFIG_HOME, and add `.dump`
file extensions.
> Document file writing behaviour of dump/restore

- sample-stumpwmrc.lisp
Need to use `nsubstitute' to mutate the string.
> fix a small typo in sample rc file macro.

- primitives.lisp
I like dformat also to print the debug level of a message.
Do you find this useful as well?
> print debug level in dformat

- stumpwm.lisp
Even when I am debugging an error I want to be able to abort debugging again as if *top-level-error-action* were set to :break.
> add restart to abort debugging when *top-level-error-action* is :break

- primitives.lisp
Was reading the docstring to use this macro, and noted that a keyword is not mentioned in the example.
> add missing keyword argument to docstring

- events.lisp
Reverts stumpwm/stumpwm#503
See https://github.com/stumpwm/stumpwm/issues/502#issuecomment-629693229
> Revert "Change xlib::make-window to equivalent `make-instance` call"

- help.lisp
This addresses issue #784 by checking if a keymap is really a keymap in the functions `get-kmaps-at-key` and `which-key-mode-key-press-hook`. The problem occurs when a key is bound to both a keymap and a command in separate maps (eg. in `*top-map*` and `*group-top-map*`)¹. At that point the function `get-kmaps-at-key-seq` returns both the keymap and the command, causing an error when one tries to display the bindings for the command (in `which-key-mode-key-press-hook`) or tries to get the keymap bindings of the command (in `get-kmaps-at-key`). 
¹We can see this by binding a keymap in `*root-map*` to a key which is bound to a command in `*group-root-map*`.
> Fix which-key-mode when discrepancies exist between top maps

- stumpwm.texi.in
Add M-f and M-b keys from Emacs.
Works in both Firefox and Chrome.
> Update Example in 2.4 Remapped Keys

- module.lisp
"like INIT-LOAD-PATH first recursively build a list of paths
that contain modules, then add them to the load path"
Open for suggestions to rename it or refactor it in a different way. But I just want to be able to add another modules directory that is handled just like the default modules directory by INIT-LOAD-PATH.
> add recursively-add-to-load-path

- command.lisp
Wrong optional argument __completions__ passed on function __argument-pop-or-read__ causing error for issue https://github.com/stumpwm/stumpwm/issues/800#issue-676053690.
> Fixing stumpwm-type :gravity and :direction

- window.lisp
At present, the hack to work around a button argument of `:any` to `grab-button` not working only grabs the first 7 mouse buttons, but there can technically be up to 32 buttons on a mouse. This PR just grabs all 32.
Additionally, `:any` appears to work on my machine now, so perhaps we should just use that instead, unless it is still broken for other people.
> Grab all mouse buttons

- bindings.lisp
- stumpwm.texi.in
Someone in IRC was asking how to undo a `bind` command.  After
grovelling around in the source I see there's no corresponding `unbind`
command and you'd have to do some kind of `undefine-key` incantation.
This adds `unbind` so you can do it more easily.
> Add an UNBIND command to undo a BIND command

- primitives.lisp
- stumpwm.asd
- stumpwm.lisp
- support/debug.lisp
The new mechanism logs to a file by default. It also keeps the two oldest
log files. This way when a user wants to enable persistent logging all they have to do is `(setf *debug-level* X)`. The previous `redirect-all-output` approach still works.
Additionally this commit adds basic support for the XDG base directory
specification. We only use it for the location of the log file, but it
could be used in the future to place the configuration file according
to the XDG base directory specification.
I would also like to slowly move things that aren't directly related to window managing responsibilities to a module named support. If you are familiar with Rails think along the lines of active support. Things like auto-complete strategies or run-prog would go there.
> Log to a file by default

- debug.lisp
This prevents TYPE-ERROR during StumpWM shutdown process.
> Fix invalid use of makunbound

- window.lisp
When redisplay is called on windows with a nil normal-hints, redisplay
throws an error. This modifies window-width-inc and window-height-inc
so they always return a number
Fixes #820
> Fix redisplay on certain windows

- stumpwm.lisp
The previous permissions were missing the executable bit so `stumwm.log` couldn't be created since it's parent directory was missing the required permission to contain files.
Set the group and other permission to `0` as I think only giving them execute permissions won't enable those entities to access this directory.
> Initialize the data dir with 0700 permissions

- remap-keys.lisp
This appears to be a simple matter of switching out read-key
for read-key-no-modifiers so that it sends a full key chord
instead of a single keypress
> Fix send-raw-key

- head.lisp
For example, on Android with XServer XSDL, randr capability is detected but cannot at present be used.
> Recover if randr version of make-screen-heads fails.

- primitives.lisp
- stumpwm.lisp
This PR is offering 2 commits:
- The first one exposes a new hook that runs before any threads have been spawned, as SBCL requires an application to have no threads for sb-posix:fork to work
- The second one exposes a new function to close all the resources in a child process; I had a lot of weird sessions until I realized I should close the X display in the child :)
> Allow forking from within the ~/.stumpwmrc

- stumpwm.asd
- stumpwm.lisp
_I gather this will be slightly more controversial... but I still suggest as it gives a means to salvage your X session on heavy problems._
FORCE-STUMPWM-RESTART will immediately force a restart outside stumpwm's
loops and is kind of harsh.
Sometimes when debugging I cannot invoke the command RESTART-HARD anymore.
But you cannot call RESTART-HARD from a swank as it needs to be in the
context of the CATCH :TOP-LEVEL.
The :HUP-PROCESS in function STUMPWM gave me the idea that stumpwm should
even do this when receiving SIGHUP and this is kind of nice so that you
can restart stumpwm even when you cannot invoke commands properly and you
do not have a running swank server anymore (which sometimes happens for me).
> add signal handler for POSIX signal SIGHUP to force a hard stumpwm restart

- stumpwm.asd
- stumpwm.lisp
see discussion in https://github.com/stumpwm/stumpwm/pull/774
> get rid of CFFI dependency by using rewriting set-signal-handler to use SBCL's Foreign Function Interface directly

- Makefile.in
- stumpwm-tests.asd
This change will cause all of the test packages known by fiasco to run. Since only test packages that we care about should be loaded, no unneeded work should be done, but it will allow us to break up our tests into multiple packages if needed. Currently, only tests in the `:stumpwm-tests` are ran.
Note that these changes are also present in #839, but since that PR probably isn't going to be merged, I'm submitting this separately.
> Use `fiasco:all-tests` to run tests instead of run-package-tests

- floating-group.lisp
Set up `*float-group-top-map*` and `*float-group-root-map*` in the same
way as `*tile-group-top-map*` and `*tile-group-root-map*`: by initializing
them to `nil` and using `fill-keymap` to populate them with bindings.
I noticed that bindings created in `*float-group-root-map*` weren't actually being bound, and after inspecting the variable `*float-group-top-map*` I found it to be empty; `*escape-key*` wasnt bound in it the same way it is in `*tile-group-top-map*`. This ammends that by initializing the `*float-group-*-map*` variables in the same manner as the `*tile-group-*-map*` variables.
> Set up floating group root keymap in the same manner as tiling group

- fdump.lisp
If the name passed into various dump commands is an absolute path, it will be used as
is. Otherwise, it will default to XDG_DATA_HOME/stumpwm/NAME.dump, as previously
implemented to resolve #746. The prior behavior also broke winner-mode, which
dumps in /tmp/.
Tested:
* winner-mode works as expected (absolute path)
* Interactively dumping with `dump-group` and `restore-group` with a name works as expected
Fixes:
* https://github.com/stumpwm/stumpwm-contrib/issues/189
* https://github.com/stumpwm/stumpwm/issues/746
> Allow absolute paths when dumping and restoring dumps

- tile-window.lisp
While testing #851 we found a bug where if a fullscreen window is moved to a group that has never had a window in it, StumpWM tries to call `window-parent` on `nil`. This is due to the way the function `geometry-hints` handles fullscreen windows. This pull request moves the offending code into a `when` statement dependent upon `group-raised-window` being truthy.
> Check for nil value before calling `window-parent` within `geometry-hints`

- input.lisp
This PR adds two customizations for input-related functionality:
* `*input-completion-show-empty*`: When t, show completion candidates even when the input string is empty. Set to nil by default to maintain the existing behavior of not showing the completion candidates.
* `*input-candidate-selected-hook*`: A hook variable. Hook functions are called with the input string when an input is selected.
These two customizations, plus the `*input-refine-candidates-fn*` variable from [my last PR](https://github.com/stumpwm/stumpwm/pull/857), have allowed me to implement a prescient.el port for stumpwm: https://github.com/landakram/stumpwm-prescient. Basically, it remembers selected inputs and sorts the input candidates by frecency.
> More customization for input

- color.lisp
- command.lisp
- timers.lisp
`cl:nth-value` can be used to access an nth return value. The `(first (multiple-value-list ...))` in `timers.lisp` is not needed since functions like `/` ignore additional return values by default.
> remove unnecessary uses of multiple-value-list

- window-placement.lisp
The `match-properties-or-function` value was incorrectly used.
> Typo fix: match-properties-or-function -> match-properties-and-function

- dynamic-group.lisp
This addresses an issue encountered by @jcguu95 where stumpwm would crash if a dynamic group is created, a single window added, and then that window gets removed. Dynamic groups would try to focus the master frame, which at that point in time was nil. This PR ensures that the master frame is set from the get go.
> Dynamic tiling fix error on removing first and only window from group

- dynamic-group.lisp
- stumpwm.texi.in
- tile-group.lisp
- Add command `vsplit-uniformly' with the same behavior as
`hsplit-equally'.
- Deprecate `hsplit-equally' in favor of `vsplit-uniformly'.
- Add command `hsplit-uniformly' with the same behavior as
`vsplit-equally'.
- Deprecate `vsplit-equally' in favor of `hsplit-uniformly'.
This fixes #854.
> Add [vh]split-uniformly, deprecate [hv]split-equally.

- message-window.lisp
- primitives.lisp
- stumpwm.texi.in
The `*timeout-wait*` variable specifies how long a message will appear for. One might want shorter messages to disappear a lot sooner than long ones.
This PR adds makes the timeout differentiate between single- and multiline messages and adds a variable `*timeout-wait-multiline*` for the multiline ones.
> Add *timeout-wait-multiline*

- window.lisp
I encountered a problem where GnuCash windows don't get any StumpWM keybindings, effectively disabling window management while a GnuCash window was focused. Debugging it turned out what appears to be that GnuCash's splash-screen window goes away before the map-request of the main window has completed processing, and when updating the group and remaximizing all windows in it, `UPDATE-CONFIGURATION` gets into trouble because of that, unwinding back to `HANDLE-EVENT`, leaving the main window in a state of only being half-setup.
I can't say I'm sure that just ignoring those errors is the right way to solve this problem, but I at least don't think it should cause any problems, since a dead window shouldn't need any configuration notifications.
> Ignore `XLIB:DRAWABLE-ERROR` in `UPDATE-CONFIGURATION`

- command.lisp
I kept trying to call commands with arguments like `t`, which `:y-or-n` evaluates to `nil`, which confused me. So i made `:y-or-n` throw an error if the argument isn't `"y"` or `"n"`
alternatively, we could create a list of arguments that evaluates to `t`, i would propose `t`, `"t"`, and `"Y"`
let me know what you think!
> be more stringent about string inputs to "y or n" prompts

- command.lisp
* command.lisp (:y-or-n):
The body was placed in let varlist by mistake. I moved it out.
> Fix compile error: fix let binding body position

- floating-group.lisp
When moving the window from a group to another, the window is marked as hidden, then it is actually
hidden, and group is asked to process lost focus. For float groups, the window focus lost function
picks up the next window in the group, even when it is hidden.
This patch doesn't allow a hidden window to gain focus.
As a side effect, `hide-window` now works for the last window of a floating group (need to verify that it wasn't working).
> Fix moving last window of floating group to another group

- primitives.lisp
The compiler will now ensure that *TOP-LEVEL-ERROR-ACTION* will only be one of the prescribed values. This is useful because toplevel errors are handled in an ECASE expression, so if *TOP-LEVEL-ERROR-ACTION* contains an unexpected value at the time of a toplevel error, the expression will cause another, more cryptic error to be signaled.
> Add a type declamation for *TOP-LEVEL-ERROR-ACTION*

- keytrans.lisp
I notice that the symbol £ wasn't included in the keytrans file, for people that use the english UK layout it maybe useful.
> Add the sterling pound to keytrans

- tile-window.lisp
Raising fullscreen windows in `geometry-hints` causes problems when new windows are created in a group which has an unfocused fullscreen window open. Also, it does not seem like a very good idea to be changing window orders in a function meant to get properties, as earlier discussed [here](https://github.com/stumpwm/stumpwm/issues/632#issuecomment-521786107).
If anyone knows if there is a good reason the function was written to raise fullscreen windows, I can write a patch which still respects that, but for now this seems like the solution to this issue.
> Don't raise fullscreen windows in GEOMETRY-HINTS

- tile-group.lisp
Quick one-liner to cause tile-group-float-window to update the window decorations. As it stands, each floated window uses the default decoration settings and doesn't follow the user's settings until it loses or regains focus.
> Update window decorations when a tiled window is floated

- primitives.lisp
- window-placement.lisp
* Fix typo causing hard crash
when using `match-properties-and-function` alone a typo was causing it to funcall `match-properties-or-function` instead, which caused a hard crash from which one cannot recover.
* update docstring
Update docstring for `define-frame-preference` to accurately reflect the acceptable values for `match-properties-[and|or]-function` key arguments.
> Patch window placement rules

- floating-group.lisp
For float groups, when moving window to another group, the target group was selected automatically.
This patch fixes this by adding the raise parameter - similar to tiling and dynamic groups.
> Call group-focus-window only when requested

- floating-group.lisp
When a window is maximized it can move to the wrong head, depending on whether left/top is matched or right/bottom is matched first in the list of heads. This patch makes it choose the same head independent of the head list order.
> Fix window head selection on full screen

- help.lisp
- kmap.lisp
- stumpwm.texi.in
This commit adds two new customizable variables:
- \*key-seq-color\*
- \*which-key-format\*
The former modifies the color of keybindings color as shown in the
prefix string in the which-key-mode windows.
The latter modifies how keybinds are displayed in the which-key-mode
windows.
Although \*which-key-format\* relies on \*key-seq-color\* when
initializing its value, if the latter is updated, it will be necessary
to also update the former.
> No hardcoded keybindings colors and which-key format

- help.lisp
A missing tilde makes all keybinds appear as `5a`. This commit fixes this.
> Fix default format for which-key

- help.lisp
This PR displays keybindings and keymaps in the `describe-command` message. It adds two functions, `find-binding` and `find-binding-in-kmap` which recursively look through the specified keymaps (and all sub-maps) and return a list of bindings that match the specified command. 
Here is some screenshots of `describe-command`:
This improves StumpWM by improving discoverability and self-documentation capabilities. It also addresses the issue of users undefining a key in `*root-map*` when the binding they wish to remove is in `*[tile|float|dynamic]-group-root-map*` by making it clear which map it is bound in. 
I would appreciate a review of this, as the formatted table of bindings is placed outside of the `wrap` function, as that function removes extra spaces which are needed for the …
> Display keybindings in `describe-command`

- window-placement.lisp
Fixed typo introduced in 5c077c7e94abf7079d187f8ccb9274144ea4cf83
> Typo fix: group -> new-group

- main.lisp
- stumpwm.asd
This is a starting point for my suggestion in https://github.com/stumpwm/stumpwm/pull/813
To generate the executable in a REPL evaluate:
(asdf:make "stumpwm/build")
This creates an executable named stumpwm on the current directory.
Before we could merge this we would still need to use `(uiop:command-line-arguments)` to have a CLI option to extract the manual instead. With this change we could simplify the stumpwm rule in the Makefile to be just stumpwm, the file.
> Add program-op to build StumpWM using only ASDF

- color.lisp
- primitives.lisp
- stumpwm.texi.in
This PR adds the ability to ignore color formatters (such as `^(:fg "red")`). While likely not a big deal for many, I find it useful to suppress color formatters, such as when displaying notifications through StumpWM. 
Edit: apologies, I tried using githubs fetch upstream functionality, and it seems to have added an additional commit. I will remove this.
> Add ability to ignore color formatters

- dynamic-group.lisp
This commit patches the method group-remove-head when called with a dynamic group to ensure that operations expecting a list will receive a list. This should resolve #956.
> Patch Dynamic Group Head Removal

- tile-window.lisp
`unmaximize` is a command that is useful from Lisp, not just interactively. Because it assumes the current window, it is not possible to use it from functions in `*new-window-hook*` since they are called prior to the new window being made the current one. This fixes that by allowing you to specify a window when calling it from Lisp. Interactively, it still defaults to the current one.
> allow `unmaximize` command to accept a window as its argument

- mode-line.lisp
This patches the function `redraw-mode-line` to catch errors during the expansion process and during the rendering process. The motivation for this is that I have seen StumpWM users, often newer users, crash StumpWM by using a non-valid mode line format string. 
Should an error be caught one of two strings will be displayed in the mode line, telling the user that the mode line could not be expanded/rendered, and displaying the error that was caught.
> Catch errors when expanding and rendering mode line format strings

- primitives.lisp
- stumpwm.texi.in
- tile-window.lisp
This PR allows for windows to be made fullscreen within their frame instead of their head. By default all windows will fill the head when being made fullscreen, it is only by defining a rule that they are made fullscreen within the window. The rule add/remove functionality was placed in `primitives.lisp` along with the rule defining macro, as this is where `define-frame-preference` is defined, but if there is a better location they can be moved there. This would address issue #971.
This PR doesnt change the default behavior, and windows fullscreened within their frame can coexist with normal fullscreen windows (tested with firefox and vlc). The usage of keys in an alist allow for temporarily overriding a rule, or adding rules that run only once; users could define a macro such as: …
> Add in frame fullscreen functionality

- input.lisp
- kmap.lisp
- stumpwm.texi.in
This PR implements preliminary support for altgr key bindings. This wont allow all keys to be input in the input bar, but it will allow binding to keys that can only be pressed with altgr. For example, the `[` key lies on altgr+8 when using the no layout, and this allows entering that key in the input bar, as well as binding commands and keymaps to it. 
While this is 100% a problem that should be solved in CLX instead of here, there has been little progress on it and it seems unlikely to be implemented soon, so this is presented as a workaround to address issues such as #936. 
Certain characters fail to be looked up properly, but I'm unsure if this is an issue specific to my own setup or not. For example, while `lstroke` gets registered properly for binding keys, the keysym that it gets …
> Add preliminary altgr support

- dynamic-group.lisp
Removed a todo to change a list to an array, as the list size is small enough
that access has a negligible impact on performance.
Removed a todo to move superfluous window tracking, as it is no longer
relevant.
Changed documentation of HEAD-INFO-ALIST slot to refer to FIRST, SECOND,
etc. instead of CAR, CADR, etc.
> Removed irrelevant todos, made documentation clearer

- tile-window.lisp
hey, i wrote a big wall of text here, but wonderful firefox browser crashed the tab with no survivors, so forgive me if this is not complete or it sounds bad
i tried out the code in #974, and it didn't really work well for me, it left space at the top when i fullscreened a frame. probably has to do with the fact that @szos has the modeline at the top, and i have it at the bottom. i modified the code so that there's no manual checking of the modeline height and stuff, since there are frame-display functions to handle all that. there was also a comment saying there is a check on whether we are fullscreening a frame or head, but there was no such check, so i added it. the code should probably be changed a bit or something, i don't know lisp so i don't know what is good style/performant. …
> Fix fullscreen frame

- minor-modes.lisp
- mode-line-formatters.lisp
- tile-group.lisp
- tile-window.lisp
Update various things related to minor modes: 
- change a condition type
- update the minor mode mode line formatters
- export autoenable and autodisable generic functions to allow ease when defining methods for them
- make the functions `sync-frame-windows` and `geometry-hints` generic to allow specialization by minor modes. 
- added on-click option for minor modes and setup the default on-click behavior
> Minor mode updates

- group.lisp
Currently the commands `gprev-with-window` and `gnext-with-window` only raise the window, and dont focus it. While this works with tile groups, it falls short with float groups. This patch fixes that. 
Steps to reproduce the bug: 
1. open a window in a tile group
2. run `gnewbg-float flt`
3. run `gnext-with-window`
4. run `info` and see that there is no current window.
> patch group-forward-with-window to focus window

- head.lisp
- tile-group.lisp
- tile-window.lisp
This resolves the crash in #647 and #763 . 
Ultimately, this happens because `group-remove-head` can't handle there not being any frames in a group. If you try to remove the only head, `group-remove-head` will delete its frames from the group's `tile-group-frame-tree`, leaving it empty, then it will try to grab the group's first frame `;; just set current frame to whatever.`, which will, unfortunately, be nil, and proceed to set all of the windows' window-frame to nil, causing this problem.
https://github.com/stumpwm/stumpwm/blob/master/tile-group.lisp#L196-L208
This pull request solves the problem by simply preventing there from not being any heads during normal operation: adding new heads before removing the old ones if both happen in a single `:CONFIGURE-NOTIFY ` event.
I do, however, …
> Made scale-screen add heads before removing heads

- AUTHORS
- Makefile.in
* Use --non-interactive so that build failures exit with a non-zero error code
* Set sb-impl::*default-external-format* to :UTF-8 based on this StackOverflow:
https://stackoverflow.com/questions/22822793/running-utf-8-encoded-scripts-with-steel-bank-common-lisp
This should fix issues 1012 and 1013 and fix the pipeline build for PR 1011
> Update SBCL options in the Makefile

- AUTHORS
- ioloop.lisp
This fixes [Issue 994](https://github.com/stumpwm/stumpwm/issues/994), caused by SBCL [removing `#'sb-unix:unix-select`](https://github.com/sbcl/sbcl/commit/856a6ac26f2e7ac74d5f26cd4390bc1bd7e63c4e)
> Fix 994: Replace sb-unix:unix-select with sb-unix:unix-fast-select

- events.lisp
- window.lisp
This fixes an issue that is quite possibly a bug in Chromium. Given the following steps:
1. Run a Chromium-based web browser
2. Visit a site with a menu that opens on hover
3. Hover over the menu to open it
4. Click an item in the menu
The expectation is to be clicking the menu item. Instead the menu would close and the click would pass through to the element underneath.
This issue could be worked around by passing the following option to Chromium:
--disable-features=SendMouseLeaveEvents
In the source code, this feature is explained as follows:
This feature allows native ET_MOUSE_EXIT events to be passed through
to blink as mouse leave events. Traditionally these events were
converted to mouse move events due to a number of inconsistencies on
the native platforms. crbug.com/450631
With …
> Grab buttons on managed window instead of parent

- color.lisp
- screen.lisp
This is a hacky, partial fix for #669, also experienced by elais[m] on IRC, in which enabling a compositor turns the StumpWM window background color transparent. It's based on [a similar fix](https://github.com/herbstluftwm/herbstluftwm/pull/1178) in herbstluftwm.
Since this patch changes the result of a call to `xlib:alloc-color`, which involves a request to X, I suspect it to break on systems that don't use 24-bit colors. I'm not sure how to properly test that.
It would probably be better to either do this in our `alloc-color` or to somehow fix this in CLX.
> Add an alpha channel to some allocated colors

- ioloop.lisp
1451b05 fixed the issues with unix-fast-select returning nil, however,
it replace a call to `multiple-value-call` to one with
`multiple-value-bind` to get the the errno. However, (compute-timeouts)
returns multiple values: seconds and milliseconds remanining in the
timeout. 1451b05 passed the seconds value, and set the milliseconds to
nil, resulting in waiting for 0 seconds and 0 milliseconds whenever
the timeout was supposed to be less than a second
I also made the syscall-level errors from this debug level 1 instead
of 5
> Fix the ioloop timeout

- menu-declarations.lisp
- stumpwm.texi.in
Set default *menu-maximum-height to prevent crashing if displaying a large amount of items in a menu. Fixes #1028
> Fix select-from-menu crashing X

- primitives.lisp
fix generating of generic functions and methods for class `head`, when `*print-case*` is configured to `:downcase`. Otherwise methods like `HEAD-X` where not defined (they where named `|HEAD-x|`, etc.)
> make stumpwm working with *print-case* :downcase

- floating-group.lisp
Fixes #1041.
If the number of screens drops to zero (e.g. when turning off the monitor, or when unplugging an external screen from a laptop before re-enabling a disabled built-in display) and floating groups exist, the window manager will crash.  This is a regression introduced in 7fa64230 - a very helpful new generic function was added to preserve the layout of tiling groups when switching screens, but no default implementation was given for floating groups.
> Fix crash when switching screens with floating groups

- floating-group.lisp
- group.lisp
- head.lisp
- tile-group.lisp
- tile-window.lisp
Follow up to #1008 
Resolves the remaining issues mentioned in #763 . When a head with unhidden windows is removed, X11 will automatically relocate those windows to a valid head. Unfortunately, this means that when `group-remove-head` would use `head-window` to lookup which windows belonged to frames on the removed head (in order to reassign them to a frame that should exist, and remove the final references to frames that should not exist), the old `frame-head` function would miss the moved windows, because it looked up by actual coordinates (and the frame has already been moved into "valid" space, on the new head). This PR makes 'frame-head' a generic function, leaves the old behavior in place as a default method and adds a faster, correct, method for `tile-groups` (walking up the …
> Prevent windows from being left set to abandoned frames after xrandr events

- head.lisp
It was previously left un-destroyed, so its X11 window would block any new modelines created after a head had been replaced with its mode-line active
> Move the mode-line too when replacing heads

- color.lisp
- stumpwm.texi.in
I have been having difficulty reading some of the messages (especially from the `eval` command) because the colors are too dark. By default, the current implementation of `update-color-map` subtracts 25% brightness to create the normal colors and adds 25% brightness to create the bright colors. With this approach, no "normal" color can ever be brighter than #BFBFBF, even though those colors are often used by default by various components of the window manager and may be too dark to read easily.
This pull request adds the ability to use color specifications of the form `(dark-color light-color)` in `*colors*`. This allows the user to pick any two colors for the dark and light colors, while maintaining compatibility with older configuration files.
Another possibility would be to update the …
> Allow specifying bright and dark colors separately

- events.lisp
This PR adds the ability to check the state of modifier keys during a button press event without modifying the api for any hooks or function calls by binding a dynamic variable to the state key list. This variable is exported.
> add button state dynamic variable

- tile-group.lisp
This is an attempt at a fix to #995.
That bug only appears when switching between two disjoint sets of monitors, e.g. plugging an external monitor into a laptop and disabling the built-in display. The crash listed in #995 appears in `show-frame-outline`, but several other crashes can also occur in this situation. The fundamental problem appears to be that the current group's `tile-group-current-frame` gets set to `nil`, and a fair amount of code around the codebase can't handle this condition.
I haven't traced the code paths completely, but I suspect what is happening is that each head in the group gets removed via `group-remove-head`, and only then do the new heads get added via `group-add-head`. This means that for some time, there are no heads (and thus no frames) in the group. At some …
> Fix crash when switching between disjoint sets of monitors

- minor-modes.lisp
- replace-class.lisp
Currently when creating a new object which should have minor modes enabled in it there comes an error of type minor-mode-autoenable-error. This causes a hard crash. To reproduce the crash define a new minor mode scoped to `:window`, with the option `(:global t)`. Enable the minor mode, causing it to be enabled in all window objects. Then create a new window, triggering the crash. 
This patch addresses this by A) establishing a restart around the autoenable error signalled in the autoenable-minor-mode method to ignore the error, B) binding a handler to invoke this restart in the replace-class around method specializing on (t t), and C) explicitly checking if an object already has a minor mode enabled in it when syncing minor modes for an object.
> Fix crash when autoenabling minor mode thats already enabled

- dynamic-group.lisp
Correct a misspelling of a variable, no longer attempting to map over a window but instead map over a list of windows.
> Patch dynamic group resize head

- dynamic-group.lisp
- dynamic-window.lisp
- window.lisp
This PR modifies the expose command to function with both floating and tiling groups, and adds an additional safety measure to prevent it from destroying the state of dynamic groups. 
All logic has been moved from the expose command to a generic function specializing upon the group type, however the way tile groups are expose-ed was preserved. 
This addresses issue #1057.
> Support float groups with expose command

- command.lisp
The interactive function for the restart EVAL-COMMAND-ERROR returns an argument list of zero arguments while the restart takes one argument. This PR makes it return a single format string similar to what would be passed if this restart were invoked via the handler established within the restart-case form.
> patch interactive function for `eval-command-error` restart in function `eval-command`

- dynamic-group.lisp
- stumpwm.texi.in
this PR adds the ability to modify the default initial values for dynamic groups before instantiating them. 
It also adds missing docstrings, and adds a dynamic group specific index to the manual under the dynamic groups section.
> Expand Dynamic Groups: allow setting default values before instantiation, expand manual

- floating-group.lisp
- head.lisp
- tile-group.lisp
This addresses issue #1058. The problem is in the function `orphaned-frames`, which assumes all groups in a screen are tiling groups. This PR removes that assumption and ignores floating groups. 
This PR ignores all floating windows in the function `screen-frames`. It also makes `group-adopt-orphaned-windows` ignore float windows, as it appears that floating windows can never be orphaned; orphan status seems to refer to frames that do not belong to a group and the windows which belong to those frames.
> patch the orphaned frames function to ignore float groups

- events.lisp
Commit d5230923 fixed a Chromium bug by changing StumpWM's window grabs to be on the managed window instead of the parent window, but that had the side-effect of StumpWM not responding to button-presses on the decoration window itself, a rather critical functionality for floating groups.
This pull-request "fixes" that problem by instead responding to the event when it propagates up to the root window (where the `child` event key indicates the actual decoration window that was clicked) and translates the click coordinates as appropriate (hopefully).
I really want to make it clear that I'm not nearly conversant enough in X11 conventions to know if this is the proper fix, though. It seems like an ugly workaround to me. d5230923 states that it brings StumpWM more in line with other window …
> Work around button-presses not working for decoration windows

- configure.ac
Sorry about the double commits in this pull request, and I'm not really sure if this is something I should have made a PR for, or if it's just expected that individuals figure out how to use autotools. This is also my first PR to a public entity, so let me know how I can do better in the future.
Anyhow...
`44f4015e993e6445d68e4f9b47265c056ac6b75d` covers the following warnings I was getting when running `./autogen.sh`:
```
configure.ac:60: warning: AC_OUTPUT should be used without arguments.
configure.ac:60: You should run autoupdate.
configure.ac:61: warning: AC_OUTPUT should be used without arguments.
configure.ac:61: You should run autoupdate.
configure.ac:62: warning: AC_OUTPUT should be used without arguments.
configure.ac:62: You should run autoupdate.
``` …
> Autoconf autoupdate

- stumpwm.asd
This hopefully fixes #1079/#1080, I could compile and `make test` ran okay.
Loading the asd didn't look necessary after this, but it might be, in which case they can coexist. Otherwise, quicklisp's dynamic-mixins has a name conflict between cl's and closer-mop's standard-generic-function.
> Small patch to fix quicklisp loading dynamic-mixins

- tile-group.lisp
- window.lisp
I don't know if display-finish-output needs to be called repeatedly like it is, but if not, this little PR moves it out of loops
( Originally asked in the IRC )
> Move display-finish-output out of loops

- README.md
Dynamic tiling is already implemented so let's remove it from the wishlist.
> [23:08:36](irc:///%23stumpwm?timestamp=2023-03-15T04%3A08%3A36.000Z) <[podiki[m]](irc:///podiki%5Bm%5D,isuser)> there is dynamic tiling already, do you mean further improvements?
> Remove mention of dynamic tiling

- tile-group.lisp
The tile-group frame tree is referenced in `TILE-GROUP-FRAME-HEAD` by the position of `HEAD` in `(GROUP-HEADS GROUP)`, not by head number. Fixes #1087
> Fix head-frame insertion

- primitives.lisp
This patch avoids the "(number) is not a string designator" error that the current version of `format-expand` gives when formatting a number.
This happens, for example, when invoking the `info` command (display information about the current window) because the standard value "%wx%h %n (%t)" of `*window-info-format*` contains the numeric options %w and %h.
> Bug fix: Avoid "... is not a string designator" error in format-expand.

- configure.ac
In commit ec07aba the autoconf version was incremented from 2.59 to 2.71. This has caused all CI builds to fail (for me at least, and a quick glance at the commit logs seem to confirm this for others) due to the autoconf requirement not being satisfied. I am unfamiliar with autoconf and the github builds feature, so this solution may not be appropriate, but decrementing the version of autoconf back to 2.59 allows building again for the CI.
> decrement autoconf version

- mode-line.lisp
I wrote this in order to update the colors of the modeline without having to toggle it on and off, which creates an ugly visual jump when done that way.
> Add refresh-colors-for-modeline to mode-line.lisp

- dynamic-mixins/dynamic-mixins-swm.asd
- dynamic-mixins/src/dynamic-mixins.lisp
- dynamic-mixins/src/package.lisp
- dynamic-mixins/src/sorting.lisp
- minor-modes.lisp
Add the options `:mix-before` and `:mix-after` to `define-minor-mode` to allow coordination between minor modes regarding what order the minor modes are mixed in. Additionally adds class sorting rules to the dynamic-mixins-swm package, contained in their own file. This allows slightly finer grained control over what order methods are called in by controlling the order of the mix list.
> Add sorting rules for minor mode inheritance order

- input.lisp
Follow emacs behaviour and allow C-i do same command as TAB.
> Add C-i as alias of TAB in input-map

- input.lisp
I was searching for a function to fuzzy-match my inputs in commands/completions and found `*input-refine-candidates-fn*`. But it is weird that it's unexported, especially given that the functions intended for it—`input-refine-prefix` and `input-refine-regexp`—are exported. This patch exports the variable so that it's usable in configs without the need for alarming `::`.
> Export `*input-refine-candidates-fn*` for consistency.

- input.lisp
This adds a new input completion function that's neither regexp nor prefix—something in between, rather.
> Add `input-refine-fuzzy` for fuzzy matching.

- tile-group.lisp
To make minor modes function with frames as a scope object, they had to be implemented as classes and not structures. The function copy-frame-tree calls copy-structure on a frame and was overlooked when this change was made, in part because no other part of stumpwm appears to call this function and so it has no impact on uncustomized stumpwm. This patch addresses this and changes the call to copy-frame instead of copy-structure.
> patch copy-frame-tree to not expect a structure

- tile-group.lisp
When splitting frames on certain resolutions the frame is not split to a natural number:
When a new window is created in the "bugged" split, stumpwm crashes.
To solve this i round the ratio multiplication done in the `ratio-or-pixel` function that is called when this happens. For me this seems to solve the problem.
> Fix frame splitting calculation

- primitives.lisp
A lot of folks on the Internet are asking themselves how to launch applications in pop-up windows in StumpWM and I just kinda stumbled on it by accident so I figured it'd be a good idea to expand the documentation to mention it explicitly.
> Documenting `:float` frame number alternative in `define-frame-preference`.

- make-image.lisp.in
`make-image.lisp` can be run via `--script` at SBCL and the last one do not load ASDF and UIOP by default on this way.
That leads to an error like:
```
Package UIOP/LISP-BUILD does not exist.
```
> Require :uiop at make-image.lisp

- primitives.lisp
This fixes issue #1180. 
StumpWM expects group numbers to grow incrementally and for their numbers to match the *group-number-map*. However because group numbers start from one the tenth group created gets the group number ten, while the *group-number-map* and associated function group-map-number report its number as zero, because zero is the tenth character in that string. Removing the zero from the string removes this inconsistency, as any group-map-number that isnt present in the string is returned via princ-to-string.
> remove number zero from group number map

- minor-modes.lisp
- stumpwm.texi.in
This PR patches minor mode scopes to utilize the filter type when returning all scope objects for a given scope. Additionally it makes changes to the manual to add an example of defining minor mode scopes.
> Patch minor mode scopes

- configure.ac
- version.lisp
Reverts stumpwm/stumpwm#1199
Need to re-work version.lisp so quicklisp can load without requiring version.lisp to be built.
> Revert "Supporting reproducible builds."

- make-image.lisp.in
When stumpwm is built in some sort of fake environment the resulted image contains cached path to that fake enviroment which migth broke quicklisp.
Here I call a standard callback which is used by uiop for :toplevel function, and, additionally clear asdf configuration from build system and reset it.
> Reset uiop/asdf after load an image

- configure.ac
- make-image.lisp.in
This one doesn't turn `version.lisp` into a template.
Addresses #1215, #1211.
> Supporting reproducible builds (another attempt).

- debug.lisp
- primitives.lisp
- stumpwm.lisp
Set the *data-dir* to directory where the user configuration file is instead of always using "~/.stumpwm.d".
> Better default data dir

- primitives.lisp
Resolving the data dir path based on probe-file's canonical path lookup of pathspec breaks users that manage their StumpWM configuration through symlinked dotfiles. The data dir would incorrectly be set to wherever the root of the symlinked file is located on the file system. This may be a read only location on e.g. systems such as Guix and NixOS, or just some random location in the case of stow. StumpWM would then incorrectly treat this random location as its data directory. This patch ensures we operate on the pathspec argument and not the truename result from probe-file.
Fixes #1225
> Use non-canonical paths when resolving default data dir

- keytrans.lisp
As far as i could find quoteleft and quoteright have no relation with the symbols < and > , the bepo layout can output ` and ’ which are already defined as grave and apostrophe.
> FIX issue #997
